### ISSUE TITLE
Create material on web programming

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#11]
Create material to fill a half day or a full day to cover:
- basic HTML authoring
- parsing and creating HTML programmatically
- reading and writing web data
- how to think like the web
- security issues

Existing material is in book/web.html.

**Comment by ptone** [comment]
to continue the brainstorm:
- basics of CSS and structure vs style
- scraping vs using REST API endpoints
- Using firebug/webkit inspector as an interactive environment and exploratory tool
- accessibility

**Comment by caitsydney** [comment]
@ctb does a whole web-development course. If I TA for him, maybe we can modify some of the starting materials for SWC use? Most of his lessons are online. He does a good job with the "how the web works" / "how to think like the web" as well as a couple of module-type lessons on security. http://ged.msu.edu/courses/2012-spring-cse-491/

**Comment by gvwilson** [comment]
All desirable, but we have six hours at most, and most of the participants will still be novice programmers.

**Comment by gdevenyi** [comment]
Does such material really support the core goals of Software Carpentry?

Also, there's a lot of material out there already that covers these topics quite well. Should we duplicate that effort?

**Comment by embray** [comment]
Given recent experiences I can say that scientists do want to build web sites and web-based mobile apps and things of that nature, and have _no_ idea how to even begin with that (or if they do they still do it poorly using 20th century technology).  So I think it's worth covering, but only for audiences that are specifically clamoring for it.

**Comment by gdevenyi** [comment]
You make a good point, I've seen many terrible websites created by professors. It seems to me as though this market segment is begging for a CMS product.

**Comment by gvwilson** [comment]
- We should be able to cover things like 
  http://www.w3.org/DesignIssues/LinkedData.html.
- Something along these lines is required by @gvwilson's current 
  employer :-)

**Comment by wking** [comment]
On Wed, Dec 12, 2012 at 08:38:08AM -0800, Greg Wilson wrote:

> - We should be able to cover things like 
>   http://www.w3.org/DesignIssues/LinkedData.html.

I think RDF and the SemanticWeb are going to be hard for novices to
digest if the've never even seen HTML.  This sort of thing makes sense
if your first impulse is “how can I get my computer to do this for
me”, but it's harder when you're thinking “I think I'm full of new
ideas, where's the coffee?” ;).

Can you break your initial topic list down into hours?  Here's the
number of lines in each section of the book (as of 605b1279):

```
$ grep -n '<h2>' book/web.html 
51:      <h2>How We Got Here</h2>
192:      <h2>Formatting Rules</h2>
433:      <h2>Attributes</h2>
602:      <h2>More HTML</h2>
956:      <h2>Processing HTML and XML</h2>
1294:      <h2>Finding Nodes</h2>
1529:      <h2>How the Web Works</h2>
1885:      <h2>Getting Data</h2>
2292:      <h2>Providing Data</h2>
2918:      <h2>Summing Up</h2>
```

This means 2918 - 192 = 2726 lines of content, and gives roughly
(assuming lines ∝ time):
- 1.7 hours ≈ (956 - 192) / 2726 \* 6:
  basic HTML authoring
- 1.3 hours ≈ (1529 - 956) / 2726 \* 6:
  parsing and creating HTML programmatically
- 2.3 hours ≈ (2918 - 1885) / 2726 \* 6:
  reading and writing web data
- 0.8 hours ≈ (1885 - 1529) / 2726 \* 6:
  how to think like the web
- 0 hours: security issues

RDF and security (HTTPS?) don't seem to be in the book chapter at all.

> - Something along these lines is required by @gvwilson's current
>   employer :-)

Something along the lines of “Linked Data”?  Or something along the
lines of “something involving HTTP”?
