### ISSUE TITLE
Blog RSS URL has changed

### ISSUE THREAD

**Issue by jrsmith3** [swcarpentry/DEPRECATED-website#112]
It looks like the RSS URL has changed since we switched over to the new website. As a result, I (and I imagine others that subscribed to the old URL) haven't been getting the past few updates.

Here's the old URL (tied to the wordpress blog, I think):

http://software-carpentry.org/blog/feed/

Here's the new one:

http://software-carpentry.org/feed.xml

I don't know if there's a way to redirect from the old URL to the new one. If not, it might be worth telling people to update their RSS feed.

**Comment by pipitone** [comment]
This is related to #100.  That fix handled /feed/, but apparently /blog/feed/ also needs to be handled.
