### ISSUE TITLE
Bundled PyRSS2Gen uses the BSD (not MIT) license

### ISSUE THREAD

**Issue by wking** [swcarpentry/DEPRECATED-website#128]
SWC claims distributed code is licensed under the [MIT license](http://opensource.org/licenses/mit-license.php), but it bundles [PyRSS2Gen](http://www.dalkescientific.com/Python/PyRSS2Gen.html), which is released under the [BSD license](http://opensource.org/licenses/bsd-license.php).  Possible solutions:
- Require maintainers to install PyRSS2Gen independently and add it to the list of prerequisites.  This is my preferred path (see [here](http://blog.flameeyes.eu/2009/03/bundling-libraries-the-curse-of-the-ancients)).
- Allow BSD-licensed code in SWC repositories (with a caveat in `license.html` and an explicit copyright blurb in the BSD-licensed file).

**Comment by pipitone** [comment]
Good catch. 

Another solution: rewrite using native python libraries.  It really wouldn't be difficult, and I'll volunteer to do it.

**Comment by scopatz** [comment]
> Allow BSD-licensed code in SWC repositories (with a caveat in license.html and an explicit copyright blurb in the BSD-licensed file).

This seems easy enough. Or actually, the easiest for all parties.

**Comment by gvwilson** [comment]
Can @wking or @scopatz submit a patch that modifies license.html with appropriate wording?

**Comment by wking** [comment]
Closed with #155 (allowing alternative licenses if they are clearly labeled in the file itself).
