### ISSUE TITLE
Issue badges to instructors, creators, and organizers

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#14]
1. Build a command-line script for issuing open badges using 5.0/bin/*.py as a starting point.
2. Use this to issue badges to instructors, creators, and organizers. (We won't issue to learners until we figure out what that means.)

**Comment by npch** [comment]
Question: are we going to be collecting and storing details of instructors, helpers and organisers in a "standard" format for each bootcamp? So that then you could just run a script after each workshop once the organiser/instructors have confirmed attendance and written a post-mortem report?

**Comment by gvwilson** [comment]
I already have these details in a little SQLite database --- it's not 
public because it contains personal information (e.g., email addresses 
and phone numbers).  We should figure out where/how to store this 
securely in a shareable way.
Thx,
G

**Comment by wking** [comment]
On Mon, Dec 10, 2012 at 01:06:43PM -0800, npch wrote:

> Question: are we going to be collecting and storing details of
> instructors, helpers and organisers in a "standard" format for each
> bootcamp?

+1 for structured data.  Boot camp YAML front matter in
boot-camps/gh-pages would be a good place for this.  If this
information is not going into the websites or related content, storing
it somewhere else may be ok.  I'm not sure it's worth the mental
overhead of having two (or more) places where boot-camp details are
kept.

**Comment by gvwilson** [comment]
See https://github.com/swcarpentry/website/issues/43.

**Comment by wking** [comment]
On Mon, Dec 10, 2012 at 01:12:09PM -0800, Greg Wilson wrote:

> I already have these details in a little SQLite database --- it's not 
> public because it contains personal information (e.g., email addresses 
> and phone numbers).  We should figure out where/how to store this 
> securely in a shareable way.

Private Git repo for the sqlite file?  I'd probably publish it on
software-carpentry.org over HTTPS and have a single user/password
simple-auth requirement.  This is not very secure, but the personal
information doesn't seem very sensitive.

**Comment by gvwilson** [comment]
Badges issued 2012-12-20.
