### ISSUE TITLE
Build Popcorn-based replay-with-audio plugin for IPython Notebook

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#15]
Use [Popcorn.js](http://popcornjs.org/) and some kind of text-record-and-playback tool to create a replay-in-the-browser plugin for the IPython Notebook.

**Comment by jiffyclub** [comment]
See for starters https://github.com/ptone/nbcast.

**Comment by wking** [comment]
When I asked about TowTruck [1](http://github.com/mozilla/towtruck), Ian Bickering also pointed me towards
Browser Mirror [2](http://github.com/mozilla/browsermirror).  Both are works in progress, but deal with passing
DOM events between browsers.

**Comment by wking** [comment]
See also, ipython/ipython#2832.
