### ISSUE TITLE
Write bullet point summary and cheat sheet for SQL and relational databases

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#154]
- Work with @ethanwhite.
- Supercedes #70.
- Put Markdown draft in swcarpentry/boot-camps/db.md

**Comment by acviana** [comment]
Hi, so what form should this content take? Ipynb? Txt? Pdf? Roughly a page for the cheat sheet?

**Comment by ethanwhite** [comment]
As per Greg's email everything should be in Markdown.

I just posted a draft of the outline as a pull request for comment:
https://github.com/swcarpentry/boot-camps/pull/5

**Comment by ethanwhite** [comment]
The pull request was accidentally merged, so just take a look at [the file](https://github.com/swcarpentry/boot-camps/blob/master/sql_outline.md) and let me know if you recommend any changes.

**Comment by ethanwhite** [comment]
And a draft of the Cheat Sheet is now up as a pull request for comment:
https://github.com/swcarpentry/boot-camps/pull/7

**Comment by wking** [comment]
Closed with swcarpentry/boot-camps@9ca9cd02fbcf7542b4d229a2fdde780eea095b39.
