### ISSUE TITLE
Boot camp for HHMI

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#162]
- Contact at Howard Hughes Medical Institute is Gabe Murphy
- http://software-carpentry.org/bootcamps/2013-05-hhmi.html

**Comment by gvwilson** [comment]
- @adina is interested in instructing
- Most likely dates are May 2-3 or May 6-7

**Comment by selik** [comment]
I'd like to join as an instructor.
I expect to have helped out with at least one bootcamp by then.

**Comment by qingpeng** [comment]
I'm glad to be a backup instructor or TA. :)

**Comment by wltrimbl** [comment]
I could TA for this one if needed.
