### ISSUE TITLE
Boot camp for Tufts University

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#163]
- June 3-4 at Boston campus
- Instructors are @jesstess, @ahmadia, @selik, @wltrimbl

**Comment by selik** [comment]
That'd be great. I'll be a Boston local by then.

**Comment by ahmadia** [comment]
I'm a maybe coming from London (I can handle my own housing).

**Comment by wltrimbl** [comment]
I can help with either of those dates and can handle my own housing.
