### ISSUE TITLE
Move all existing content into Git repository

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#17]
Move everything from http://svn.software-carpentry.org/swc/5.0/website into GitHub.

**Comment by ethanwhite** [comment]
I believe I remember someone (maybe @jiffyclub) suggesting on the mailing list that we might not bother moving the history. Given the relative ease of [svn2git](https://github.com/nirvdrum/svn2git) for bringing along the history it seems like it might be worth the extra bit of effort to do so (I've done this fairly regularly as my group has made the transition without much trouble). We can even use svndumpfilter if we need to break the repository up into separate repositories during the process.

**Comment by gvwilson** [comment]
Over the years, some things have been added to the SVN repo that should never have been there (e.g., PDFs of research papers that we didn't have permission to share). I'd be happy at this point to lose the history, since the SVN repo will always have it if we really, really want it.

**Comment by ethanwhite** [comment]
OK, sounds good to me.
