### ISSUE TITLE
Create a one-minute video pitch "why you should attend a Software Carpentry workshop"

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#18]
Write, record, and post a 60-second video explaining what we do and why potential learners should come to one of our workshops. This can use the existing 90-second pitch as a starting point.

**Comment by ctb** [comment]
On Sat, Dec 08, 2012 at 11:40:36AM -0800, Greg Wilson wrote:

> Write, record, and post a 60-second video explaining what we do and why potential learners should come to one of our workshops. This can use the existing 90-second pitch as a starting point.

We should do discipline specific ones, too.

## --titus

C. Titus Brown, ctb@msu.edu

**Comment by caitsydney** [comment]
What about comments from people who have taken the workshop? "Why SWC was useful to me" sort of thing. Possibly record at workshops (during, after) about why people are attending and what they hope to learn.

**Comment by npch** [comment]
This short interview that Mike did with the EGI might be of use as one starting point:
http://www.egi.eu/news-and-media/newsfeed/news_0178_software_carpentry_workshop.html
