### ISSUE TITLE
Some URLs showing up in Google are not resolving

### ISSUE THREAD

**Issue by ethanwhite** [swcarpentry/DEPRECATED-website#185]
I just ran across a http://software-carpentry.org URL in Google's index that isn't resolving on the new site:

http://software-carpentry.org/blog/2012/01/settings-our-sights-a-little-bit-lower/trackback/

It 404s on a slightly different page:

http://software-carpentry.org/blog/2012/01/settings-our-sights-a-little-bit-lower/trackback.html

Without the `trackback` portion of the URL it resolves fine so I'm guessing this is a WP thing that we aren't currently handling properly in .htaccess?

**Comment by gvwilson** [comment]
Good catch --- Jon?
Thx,
G

**Comment by pipitone** [comment]
Ethan's right.  We're currently not handling trackback URLs.

Perhaps a 410 (Gone) error code is more apt?

Jon.

**Comment by gvwilson** [comment]
Jon's call.

**Comment by pipitone** [comment]
Okay, I'll work on a fix to return a 410.

**Comment by pipitone** [comment]
Fixed in commit 69a1c11
