### ISSUE TITLE
Inconsistent use of "Workshop"/"Boot camp"

### ISSUE THREAD

**Issue by amyrhoda** [swcarpentry/DEPRECATED-website#198]
On the Boot Camps page (http://software-carpentry.org/bootcamps/index.html) the subheads refer to Boot Camps as Workshops. Even if we occasionally refer to boot camps as workshops (particularly when defining the "boot camp" terminology) we should use Boot Camp in headers.

**Comment by gvwilson** [comment]
Everything should be 'boot camp' (with the space, not one word). Please edit where needed.

**Comment by amyrhoda** [comment]
Do we need a style sheet? Or is that my inner obsessive editor talking? ("Inner?")

**Comment by wking** [comment]
Since 6ce9f81e2fd1e5746a77881a744edc1f69f583cf (PR #325), the headings have “Workshops” replaced by “Boot Camps”.  That seems to address the main issue here.  I don't understand the references to style sheets though, so I may be missing something important…

**Comment by gvwilson** [comment]
Fixed by https://github.com/swcarpentry/website/commit/6ce9f81e2fd1e5746a77881a744edc1f69f583cf
