### ISSUE TITLE
Design PDF certificate for DiRAC "driver's license" exam

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#202]
People who successfully complete the "driver's license" exam we have put together for the DiRAC supercomputing consortium (http://www.stfc.ac.uk/Our+Research/24711.aspx) will need a PDF certificate as well as a badge of some kind.

**Comment by wking** [comment]
What about a prettier version of:

![dirac-drivers-license](https://f.cloud.github.com/assets/209920/194658/164f44dc-7fb6-11e2-9971-cae149bc31e9.png)

It ties in δ and driving, but lacks any SWC hammers/nails.  It might also throw folks off by impersonating a warning sign…  Dia source available on request, although it's probably best if someone graphically inclined just starts from scratch ;).

**Comment by gvwilson** [comment]
The version in the repo is what the stakeholders signed off on, so it's 
what we're going with.
Thanks,
Greg

**Comment by wking** [comment]
On Mon, Feb 25, 2013 at 08:17:52PM -0800, Greg Wilson wrote:

> The version in the repo is what the stakeholders signed off on, so
> it's what we're going with.

Err, which version in the repo?  And if you have something you're
happy with, it would probably be a good idea to close the bug ;).
