### ISSUE TITLE
Bootcamp for Wuhan Institute of Virology

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#207]
- Summer 2013
- @kcranston is organizing
- Prefer people who are already in East Asia (to keep travel costs down)

**Comment by gvwilson** [comment]
@karthikram is interested

**Comment by karthik** [comment]
Karen: Just to repeat what I told Greg, if someone can cover my airfare from Hong Kong, I could do this. Let me know.

**Comment by qingpeng** [comment]
I may go back to China this summer. (80% chance)
I will stay three to four weeks if I can make it. If that period can
cover the date of the boot camp, I am interested in helping the
teaching.
