### ISSUE TITLE
Run boot camp at Telecom ParisTech

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#210]

**Comment by gvwilson** [comment]
- We have room for approx. 140 people.

**Comment by katyhuff** [comment]
Is there a date? Do they have the cash to fly people across the ocean? I might be free-ish in the summer...

**Comment by emhart** [comment]
I could totally do it if there's money to fly people across the ocean :)

**Comment by agramfort** [comment]
hi,

the bootcamp is on april 20-21. I don't think we'll have money to fly
people over the ocean so we'll likely do with the locals / europeans.

cheers,
Alex
