### ISSUE TITLE
Boot camp for University of Dundee

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#213]
- Local contacts are Jim Procter (rocter@compbio.dundee.ac.uk) and Chris Cole (chris@compbio.dundee.ac.uk), Computational Biology

**Comment by mikej888** [comment]
10/01/13 Neil Chue Hong sent Jim and Chris info about boot camps after they expressed interest. They're the same group as Nancy Giang (who attended Newcastle and helped at Edinburgh - potential first time instructor if we run one in Dundee?!)

**Comment by mikej888** [comment]
Closing boot camps which have no date. These tentative prospects are tracked in the Software Carpentry administrator Subversion repository.
