### ISSUE TITLE
Rationalize online accounts for Software Carpentry

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#22]
Right now, we are using:
- 'analytics@software-carpentry.org' and 'workshops@software-carpentry.org' on Google itself
- 'events@software-carpentry.org' on EventBrite
- 'video@software-carpentry.org' on YouTube
- 'gvwilson@third-bit.com' for the CafePress store, Doodle, and SurveyMonkey
- 'softwarecarpentry' at Disqus

There should be a single 'admin@software-carpentry.org' account that owns/runs everything.

**Comment by pipitone** [comment]
From what I can see, our analytics account on Google is now under admin@, as is EventBrite, doodle, and SurveyMonkey, and Disqus.

There isn't a nice way to change Youtube accounts without re-uploading all of the videos, so I suggest we just stay with video@. 

CafePress still seems to be under gvwilson, but I can't log in to change it.  Greg?

**Comment by pipitone** [comment]
Okay.  Are there any other accounts to reconcile then?

**Comment by gvwilson** [comment]
Can't think of any.

**Comment by pipitone** [comment]
Great!
