### ISSUE TITLE
Boot camp at University of Oslo July 3-4, 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#222]
- Lex Nederbragt and Karin Lagesen will host
- In conjunction with the Galaxy meeting in Oslo

**Comment by karthik** [comment]
I'm interested.

**Comment by rhiever** [comment]
Tempting. I'll likely be heading across the pond July 6-10 for GECCO, so...

**Comment by davidmam** [comment]
I am rather tempted... Haven't been there for 1o years and a return visit is probably overdue.

**Comment by selik** [comment]
Yes. I definitely want to go to Oslo.

**Comment by davidmam** [comment]
Just noticed this has the Galaxy meeting as well. Makes it more interesting.
