### ISSUE TITLE
Make Facebook and Google+ Presences

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/DEPRECATED-website#231]
@swcarpentry only has a social media presence on [Twitter](https://twitter.com/swcarpentry), which is really not too popular outside the tech elite. Have we thought about expanding our social media broadcasting?

**Comment by benwaugh** [comment]
Not disagreeing, but as a newcomer to social media (now on Twitter and Google+ but emphatically not on Facebook) it isn't obvious to me why we should do this. Who are we trying to reach and what effect do we want to have?

**Comment by jiffyclub** [comment]
Social media is really the only avenue we have for broadcasting messages besides the blog. And unless people have the blog via RSS they aren't even likely to know when that's updated. And aren't we trying to reach everyone?

**Comment by gvwilson** [comment]
Assigning social media to Amy.

**Comment by npch** [comment]
I am happy to help out with the Facebook page admin/moderation (I'm not a Google+ fan as the API is so restrictive).

**Comment by amyrhoda** [comment]
Neil, I tried to add you to the Facebook page as an administrator but it failed (with no error message, naturally). My hypothesis is that I need the email address you signed up to Facebook with -- can you send it to me?

**Comment by gvwilson** [comment]
Did @npch get set up as a Facebook admin?  Did @mikej888?  Are we going to Google+?  Can this ticket be closed?

**Comment by npch** [comment]
I'm a Facebook admin so that side is sorted. We've got steady growth and gradually increasing interaction.
We're playing it slow as Facebook has a business model of charging you to do anything large scale...

I don't do Google+ very much, but I've seen @ahmadia active on there - perhaps he should be tapped up :-)

**Comment by kcranston** [comment]
I can do Google+.

On Wed, Feb 27, 2013 at 9:08 AM, Neil Chue Hong notifications@github.comwrote:

> I'm a Facebook admin so that side is sorted. We've got steady growth and
> gradually increasing interaction.
> We're playing it slow as Facebook has a business model of charging you to
> do anything large scale...
> 
> I don't do Google+ very much, but I've seen @ahmadiahttps://github.com/ahmadiaactive on there - perhaps he should be tapped up :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/swcarpentry/website/issues/231#issuecomment-14175172
> .

## 

```
karen.cranston@gmail.com
@kcranstn
```

**Comment by kcranston** [comment]
https://plus.google.com/communities/110811657045857717561

I need a larger version of the logo than the one in
https://github.com/swcarpentry/website/tree/master/img. Where would I find
such a thing?

On Wed, Feb 27, 2013 at 9:34 AM, Karen Cranston karen.cranston@gmail.comwrote:

> I can do Google+.
> 
> On Wed, Feb 27, 2013 at 9:08 AM, Neil Chue Hong notifications@github.comwrote:
> 
> > I'm a Facebook admin so that side is sorted. We've got steady growth and
> > gradually increasing interaction.
> > We're playing it slow as Facebook has a business model of charging you to
> > do anything large scale...
> > 
> > I don't do Google+ very much, but I've seen @ahmadiahttps://github.com/ahmadiaactive on there - perhaps he should be tapped up :-)
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/swcarpentry/website/issues/231#issuecomment-14175172
> > .
> 
> ## 
> 
> ```
> karen.cranston@gmail.com
> @kcranstn
> ```

## 

```
karen.cranston@gmail.com
@kcranstn
```

**Comment by amyrhoda** [comment]
There are a bunch of logo files here: https://github.com/swcarpentry/assets/tree/master/branding/logo.  Thanks for setting us up on Google+!

**Comment by wking** [comment]
On Wed, Feb 27, 2013 at 06:42:03AM -0800, Karen Cranston wrote:

> I need a larger version of the logo than the one in
> https://github.com/swcarpentry/website/tree/master/img. Where would
> I find such a thing?

You may be able to snip the one you like from

  https://github.com/swcarpentry/assets/tree/master/branding/logo/software-carpentry-identity-color.svg

This should probably be split into separate SVGs for each logo
element…

**Comment by kcranston** [comment]
I need something that is at least 250x250.

Who else should be admin on the group?

On Wed, Feb 27, 2013 at 9:44 AM, Amy Brown notifications@github.com wrote:

> There are a bunch of logo files here:
> https://github.com/swcarpentry/assets/tree/master/branding/logo. Thanks
> for setting us up on Google+!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/swcarpentry/website/issues/231#issuecomment-14177013
> .

## 

```
karen.cranston@gmail.com
@kcranstn
```

**Comment by embray** [comment]
I'm a Google+ advocate too.  I can help out on there if need be.

**Comment by kcranston** [comment]
Grabbed the gravatar logo.

If Amy and Mike join the community, I can promote them to moderator.

On Wed, Feb 27, 2013 at 9:59 AM, Greg Wilson notifications@github.comwrote:

> On 2013-02-27 6:54 AM, Karen Cranston wrote:
> 
> > I need something that is at least 250x250.
> > Amy, can you please help with the logo?
> > 
> > Who else should be admin on the group?
> > Amy Brown and Mike Jackson, please --- you can add me if you want, but
> > it would be a courtesy appointment :-)
> > Cheers,
> > Greg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/swcarpentry/website/issues/231#issuecomment-14177817
> .

## 

```
karen.cranston@gmail.com
@kcranstn
```

**Comment by amyrhoda** [comment]
Karen,  joined the G+ community. @mikej888, I or @npch can add you as an admin on Facebook (if you aren't already) if you send us the email address Facebook knows you by.

**Comment by npch** [comment]
@amyrbrown - I've just added @mikej888 as a Facebook admin for the SWC page.

**Comment by wking** [comment]
So, now that there are Facebook and Google+ presences, are we ready to close this issue?

**Comment by wking** [comment]
On Sun, Mar 03, 2013 at 07:09:06AM -0800, Greg Wilson wrote:

> On 2013-03-03 9:03 AM, W. Trevor King wrote:
> 
> > So, now that there are Facebook and Google+ presences, are we ready to 
> > close this issue?
> > 
> > Are there links pointing people to these communities?

Good point.  There are links to Facebook:

```
$ git grep -1 facebook.com
_base.html-        <a class="label swc-blue-bg"
_base.html:           href="https://www.facebook.com/pages/Software-Carpentry/578520005494710">Facebook</a>
_base.html-        <a class="label swc-blue-bg"
--
blog/2013/02/we-have-a-facebook-page.html-
blog/2013/02/we-have-a-facebook-page.html:<p>Software Carpentry finally has a <a href="http://www.facebook.com/pages/Software-Carpentry/578520005494710">Facebook page</a>.  Please drop by!</p>
blog/2013/02/we-have-a-facebook-page.html-
```

but `CONTRIBUTING.md` claims there should also be a `{{facebook_url}}`
setting.

There do not seem to be any links to the Google+ page yet:

```
$ git grep plus.google
blog/2012/08/please-help-the-hunter-family.html:<p>We are very sad to report that John Hunter, the principal author of the widely-used Python plotting package <a href="http://matplotlib.sourceforge.net/">Matplotlib</a>, is losing his battle with cancer. If you would like to help his family in this difficult time, please see <a href="https://plus.google.com/104831275312843762750/posts/ijGUG79JeT3">Stefan van der Walt's post</a>, or make a donation to the <a href="http://numfocus.org/johnhunter/">memorial fund</a> set up to help with his children's education.</p>
blog/2013/01/uchicago-in-january.html:<p>For the visually inclined, <a href="https://plus.google.com/photos/116439624339414215461/albums/5834172308565741937">here are some pictures</a>
```

**Comment by jiffyclub** [comment]
We could add another label at the bottom for G+, though these links should maybe also go in the FAQ or a separate "Contact" page.

Right now we've made a G+ "Community", I think we should probably also have a [G+ Page](http://support.google.com/plus/bin/answer.py?hl=en&answer=1710691), which is a bit more analogous to the Facebook org. page idea in that people can add us to their G+ circles instead of having to join a community.

**Comment by jiffyclub** [comment]
Okay, we have a G+ page at https://plus.google.com/u/0/b/114244759874490019250/114244759874490019250/posts. I can add other people as managers if you give me the email address associated with your G+ profile.
