### ISSUE TITLE
Boot camp at Notre Dame July 18-19, 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#232]

**Comment by rhiever** [comment]
Coming from MSU, I could do:

Thursday-Friday, June 13-14
Thursday-Friday, June 20-21
Thursday-Friday, June 27-28
Thursday-Friday, July 18-19

**Comment by synesthesiam** [comment]
At this point, I can only be sure about the April dates. Depending on where I intern this summer, I may be able to make the other ones.

**Comment by jdblischak** [comment]
Coming from Chicago, I could potentially do the following dates:

Thursday-Friday, April 11-12
Thursday-Friday, June 13-14
Thursday-Friday, June 27-28
Thursday-Friday, July 18-19

We are speculatively planning on running another bootcamp at University of Chicago around late spring/early summer, so my availability could change once we determine a date for that.

**Comment by gvwilson** [comment]
- Possibly synchronize with Northwestern (#242).
