### ISSUE TITLE
Run bootcamp at University of Manchester - 18-19/04/13

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#24]
- Where: Manchester
- Host: Casey Bergman (local organiser) and Carole Goble
- Audience: Internal
- Instructors: Mike Jackson (@mikej888), Aleksandra Pawlik (@apawlik), David Jones (@drj11)
- Helpers: Shoaib Sufi (@shoaibsufi), Michael Croucher
- Web site: http://software-carpentry.org/bootcamps/2013-04-manchester.html
- Registration: http://www.eventbrite.com/event/5397207192
- Mailing list: http://lists.software-carpentry.org/listinfo.cgi/manchester-software-carpentry.org
- Repository: https://github.com/swcarpentry/boot-camps/tree/2013-04-manchester
- Syllabus: See https://github.com/swcarpentry/boot-camps/blob/2013-04-manchester/README.md

**Comment by drj11** [comment]
Can i teach shell please? (am pretty flexible actually if it comes down to it)

**Comment by drj11** [comment]
same as issue #48 ?

**Comment by gvwilson** [comment]
This is a general workshop for U. Manchester --- #48 is specific to the EGI Forum.

**Comment by apawlik** [comment]
I would like to teach too: happy to do basically any of the SC modules. Well, maybe for HPC I'd rather be a helper.

**Comment by mikej888** [comment]
Happy to be lead instructor and cover introduction, conclusion and revision control.

**Comment by mikej888** [comment]
[SSI blog](http://www.software.ac.uk/blog/2013-04-19-software-carpentry-makes-its-debut-manchester)
