### ISSUE TITLE
Boot camp for GEOMAR (Kiel) May 6-7, 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#25]

**Comment by gvwilson** [comment]
Preferred dates are May 6-7 or May 9-10; audience will mostly be oceanographers.

**Comment by cozzini** [comment]
I am at disposal

**Comment by justincely** [comment]
I love the ocean!! I'd be available, if not speaking german and being half the world away isn't an issue.

**Comment by gvwilson** [comment]
- Dates are May 6-7
- @justincely and @cozzini will teach

**Comment by cozzini** [comment]
Booked on my agenda.
