### ISSUE TITLE
Boot camp for Caltech

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#26]

**Comment by katyhuff** [comment]
I'm potentially interested in helping with this, depending on the dates.

**Comment by caitsydney** [comment]
Me too.

**Comment by amyrhoda** [comment]
We're looking at August or early September for this. Let me know if you're still interested and we'll get a couple of instructors lined up.

**Comment by arokem** [comment]
I might be available, as long as there's no conflict with my BM plans :fire:

**Comment by amyrhoda** [comment]
This camp is going to be September 9-10 and I have @katyhuff, @justincely, @picken19 and @arokem down as potential instructors (@abostroem is the other instructor). Let me know who can make it. Thanks!

**Comment by justincely** [comment]
Hi Amy, apologies for forgetting about this (Azalee just reminded me about
it) but I am available for this as well.

Justin

**Comment by amyrhoda** [comment]
Thanks, @justincely -- I've put you down as the second instructor for this camp.  I just added you to the mailing list.
