### ISSUE TITLE
Run boot camp for Lawrence Berkeley National Lab March 4-5, 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#28]
- @gvwilson + 1 other to teach March 4-5, 2013
- to be followed by #247

**Comment by jkitzes** [comment]
Don't know about "organize", but I'm happy to hop up the hill as an instructor again, if that would be helpful. EDIT: I can do either of those, but probably not both.

**Comment by goxberry** [comment]
I could talk to my bosses about doing one of these. It's unlikely that I'd be able to do both, but I'd definitely like the experience. Will the latest study group be done (or nearly done) before then?

**Comment by shreddd** [comment]
Hi Greg - I plan on helping out
-Shreyas

**Comment by karthik** [comment]
I can help out too (although I'd prefer not to organize this round).

**Comment by emhart** [comment]
I'd like to help out with some of the ones happening in the Bay area..So I could do this one or the other ones in the area since it's a quick flight down.

**Comment by caitsydney** [comment]
I'd like to get some teaching experience and the chance to work with you IRL, @gvwilson.
