### ISSUE TITLE
Run boot camp at UCL - Th04/04 and Mo08/04

### ISSUE THREAD

**Issue by benwaugh** [swcarpentry/DEPRECATED-website#292]
- Where: UCL
- Host: James Hetherington (@jamespjh)
- Audience: TODO
- Instructors: James Hetherington (@jamespjh), Ben Waugh (@benwaugh), Miguel Bernabeu, Andrew Smith
- Helpers: TODO
- Web page: TODO
- Registration: TODO
- Mailing list: TODO
- Repository: TODO
- Syllabus: TODO
- Notes: Probable dates Thu 4 and Mon 8 April 2013, but room bookings not yet confirmed.

**Comment by jamespjh** [comment]
Room bookings now confirmed.

**Comment by mikej888** [comment]
Mailed James about
- Whether he or I will ping tutors@lists.software-carpentry.org and uk@lists.software-carpentry.org for helpers.
- Standard SWC blurb (e.g. http://software-carpentry.org/bootcamps/2013-02-uwash.html)
- If they want EventBrite, event page, mailing list.

**Comment by jamespjh** [comment]
I pinged tutors and uk.
