### ISSUE TITLE
Provide instructors to Oxford DTCs boot camp - 2013-05-09/10

### ISSUE THREAD

**Issue by mikej888** [swcarpentry/DEPRECATED-website#293]
- Where: University of Oxford
- Host: Jonathan Cooper (@jonc125)
- Audience: Oxford DTCs only
- Instructors: Mario Antonioletti (@marioa), Shoaib Sufi (@shoaibsufi)
- Helpers: Phil Fowler (possibly, 1 day)
- Web page: http://software-carpentry.org/bootcamps/2013-05-oxford-dtc.html 
- Registration: http://www.eventbrite.com/event/5656292122 (password-protected)
- Mailing list: http://lists.software-carpentry.org/listinfo.cgi/oxford-dtc-software-carpentry.org 
- Repository: currently, https://github.com/jonc125/boot-camps/tree/2013-05-oxford-dtc, eventually https://github.com/swcarpentry/boot-camps/tree/2013-05-oxford-dtc

**Comment by mikej888** [comment]
Pinged Jonathan, Mario and Shoaib:
- Web page will shortly appear at  http://software-carpentry.org/bootcamps/index.html#future, when pull request #308 is merged.
- Asked if they want EventBrite and mailing list set up.
- Asked that they let me know when they decide if they want to use GitHub or BitBucket for a repository.
- Asked if they want uk@lists.software-carpentry.org pinged for any interested helpers.
- Asked Shoaib and Jonathan for their GitHub usernames.

**Comment by jonc125** [comment]
I've drafted an initial page for the boot camp at http://jonc125.github.com/boot-camps/2013-05-09-oxford-dtc/, and will submit a pull request for it to go under the SWC account when we're ready to advertise. I've also made a (very initial) start on material in the same repository (https://github.com/jonc125/boot-camps/tree/2013-05-oxford-dtc).

I've never used EventBrite before - how easy is it to filter registrations, since this is a closed-access boot camp?

Pinging for helpers would be good - we'll have a few internal people, but it's looking like probably not enough!

**Comment by amyrhoda** [comment]
Re: filtering registrations on EventBrite -- what you can do is set the event to be private and password-protected. Then no-one can sign up unless they have a password.

**Comment by mikej888** [comment]
Thanks Amy. Is that OK for you Jonathan? If so I'll set it up. Likewise, do you want a mailing list?

**Comment by mikej888** [comment]
Pinged the October Oxford bioinformatics boot camp attendees to see if anyone wants to help out.

**Comment by jonc125** [comment]
Password-protected sounds good, thanks, and a mailing list would be helpful too.

**Comment by ahmadia** [comment]
@mikej888 - Out of curiosity, did I register under my KAUST email?  I didn't get the email :)

**Comment by mikej888** [comment]
@ahmadia - I was using the list of e-mails in the SWC database not the mailing list - I've added you to that database. If you'd like to help, you're more than welcome :-)

**Comment by jonc125** [comment]
The maximum number of attendees we can have is 56.

**Comment by ahmadia** [comment]
@jonc125 - I should be able to help out in May, out of curiosity, what is DTCs?

**Comment by mikej888** [comment]
@ahmadia - doctoral training centres. They manage EPSRC and ESRC UK funded PhDs in the UK. Oxfords include, http://www.dtc.ox.ac.uk/

**Comment by ahmadia** [comment]
Okay, so this is actually a fairly broad bootcamp then?  Good to know!
