### ISSUE TITLE
Develop pre-workshop assessment questionnaire

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#3]
Create and field-test a short questionnaire that will help potential workshop attendees figure out if the workshop is right for them (and tell instructors something about who they're going to be teaching). Some requirements:
1. Must take 10 minutes or less to complete.
2. Must _not_ frighten away the people we're trying most to help (but it's OK if the conclusion is "You're not ready for this").
3. Must be useful as a baseline for the post-assessment questionnaire.

**Comment by caitsydney** [comment]
It might be useful to have two types of pre-workshop assessments. The first would be the "Is SWC for you?" assessment that I think you are referring to here, which would also include info about the student's background/experience level... The second would be something a bit more detailed that students would take at the beginning of the workshop (actually sitting in the classroom) - which would be used for comparison with the post-assessment. Might be tough to fit in the "who is our audience?" "what do they know?" "why are they taking the workshop?" and all the experience questions into a 10-min online survey.

**Comment by wking** [comment]
The pre-assessment (and post assessment in #4 [1](https://github.com/swcarpentry/website/issues/4)) seem sufficiently
distinct from the website content that I could see them living in
their own repository.  Any ideas on storage location / assessment
format (HTML?).  Then we can commit the samples from the recent
conference call reminder and procede with a more structured
discussion.

**Comment by gvwilson** [comment]
Currently constructing 'assets' repository for files like this --- 
should have it in place in a couple of hours.

**Comment by wking** [comment]
On Thu, Dec 20, 2012 at 07:40:57AM -0800, Greg Wilson wrote:

> Currently constructing 'assets' repository for files like this --- 
> should have it in place in a couple of hours.

Now that it's in place and the 5.1 assements are added
(swcarpentry/assets#1), should this issue (and #4) be closed?

**Comment by gvwilson** [comment]
Replaced by https://github.com/swcarpentry/assets/issues/11.

**Comment by gvwilson** [comment]
I've opened two new tickets as replacements:
- https://github.com/swcarpentry/assets/issues/11
- https://github.com/swcarpentry/assets/issues/12
