### ISSUE TITLE
Boot camp for Exeter University, 12-13 Nov 2013

### ISSUE THREAD

**Issue by mikej888** [swcarpentry/DEPRECATED-website#300]
- Wellcome Trust Biomedical Informatics Hub, University of Exeter - Exeter campus
- Host: Konrad Paszkiewicz
- For physicists, engineers, biologists - may have some programming experience, but biologists understanding of loops etc may be limited. 
- Instructors: @drj11, @chryswoods
- Syllabus: (possible): shell, make, version control, Python and functions, Python and testing, an introduction to R (including how some of the Python good programming practice and testing material applies in an R context). Useful if examples use biological files/data sets etc.
- Page: http://software-carpentry.org/bootcamps/2013-11-exeter.html

**Comment by mikej888** [comment]
Telcon with Konrad.

Attendees are mixed - physicists, engineers, biologists - may have some programming experience, but biologists understanding of loops etc may be limited.
They will know UNIX, Perl, next-generation sequencing.
Possible boot camp topics include: shell, make, version control, Python and functions, Python and testing, an introduction to R (including how some of the Python good programming practice and testing material applies in an R context). Useful if examples use biological files/data sets etc.
There are locals willing to become instructors.
Tremough boot camp effectively "closed" since it's quite remote, Exeter one can be "open" (or "open" after Konrad has publicised it to his groups).
30 people interested so far.
Prefer to have 2 instructors do both campuses back-to-back e.g. both boot camps in one week or one TF and the next MT. Want to avoid July/August/September so current thinking is early November.
Can cover accomodation/travel expenses for UK instructors.
Would like us to set up web page, EventBrite so can get people to commit to November.
Interested in pre/post questionnaires (if using the task-based questionnaire this needs to be pitched at a very low level so not to put people off).

**Comment by drj11** [comment]
I would love to teach some of this. Can teach some or all of shell, make, version control, Python, testing, and maybe even an introduction to R.

**Comment by mikej888** [comment]
E-mailed Konrad standard blurb for a boot camp, but with the draft syllabus above, so he can forward to interested parties. I'll collect the responses.

**Comment by mikej888** [comment]
Chris Woods (@chryswoods) is available from 11th November (7th at a push) as an instructor.

**Comment by mikej888** [comment]
Jeremy Metz, University of Exeter, may attend as helper or instructor.

**Comment by mikej888** [comment]
Sent updated list of interested students to Konrad. Demand for one in Exeter (attendees from Tremough can be given accomodation in Exeter if they want to attend). Best date is anytime from beginning of November.
