### ISSUE TITLE
Boot camp for University of Wisconsin - Madison

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#31]
- April 29-30, 2013
- @stephenmcgough will instruct

**Comment by caitsydney** [comment]
I'd like to help arrange this conference. I'm interested in getting SWC at UW-Oshkosh, and going through the process of setting one up at UW-Madison would help.

**Comment by acviana** [comment]
Hi, I'd like to help as well. I'm an undergrad alumnus from the Astronomy Department living on the East Coast right now. I could probably help pull in some people from the Astronomy and Physics Departments to attend.

**Comment by gonuke** [comment]
I'll take the lead here and try to pull together some structure over the next few weeks, aiming for late April (pre Condor Week).  Might also pull something off at Spring Break, but less likely.

**Comment by katyhuff** [comment]
Of course, I can always help out in Madison. 
Maybe I can defend by late April, eh @gonuke !? :)

**Comment by amyrhoda** [comment]
We're doing another boot camp at University of Wisconsin - Madison on August 28-29 -- please let me know if you can instruct!

**Comment by acviana** [comment]
I might be able to, my schedule is still shaking out.
