### ISSUE TITLE
Boot camp for University of Massachusetts - Amherst

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#313]
- May 30-31, 2013
- @tracykteal is lead instructor

**Comment by embray** [comment]
As a UMass Amherst alumnus I would like to get in on this if at all possible.

**Comment by tracykteal** [comment]
Hi Erik,

That would be great.  We're working on figuring out dates right now.  We're thinking the last week in May or the end of June.  Would you be free either of those times?

-Tracy

**Comment by embray** [comment]
Hi @tracykteal , sorry I didn't get back sooner.  Yes, I should be available around that time.  Any idea who the audience is specifically?

**Comment by emhart** [comment]
Damn, I also would love to go back to UMass (also an alum).  If you need anymore instructors let me know :)
