### ISSUE TITLE
Add a link to the various discussion lists people can sign up for / view

### ISSUE THREAD

**Issue by pipitone** [swcarpentry/DEPRECATED-website#318]
Right now on our [contributing page](http://software-carpentry.org/about/contributing.html) we don't provide any links to our discussion lists, e.g. http://lists.software-carpentry.org. 

I think providing links for the discussion, dev, assessment, and tutors lists would be most appropriate.

**Comment by gvwilson** [comment]
Happy to add links for 'discuss'; would rather people weren't able to sign up unilaterally for 'tutors', but there's no reason not to put the archives online.  The 'assessment' list is probably going to be retired soon...
Question: I can't figure out how to allow people to self-register for the 'announcements' list.

**Comment by wking** [comment]
On Wed, Feb 27, 2013 at 05:11:37AM -0800, Greg Wilson wrote:

> would rather people weren't able to sign up unilaterally for
> 'tutors', but there's no reason not to put the archives online.

tutors@ archives already are online, and googling “software carpentry
mailing list” will turn up lists.s-c.o, so they currently aren't even
particularly hidden.  The listinfo page for tutors also explains that
subscription requests are moderated.

**Comment by gvwilson** [comment]
Please see my 'contributing' branch 
(https://github.com/gvwilson/website/tree/contributing) --- only change 
is in about/contributing.html.  Before I issue a pull request, I'd like 
to add an explanation of how people can put themselves on the 
'announcements' list, but I don't know how Dreamhost handles self-signup 
for announce lists.

**Comment by wking** [comment]
On Wed, Feb 27, 2013 at 05:42:24AM -0800, Greg Wilson wrote:

> Before I issue a pull request, I'd like to add an explanation of how
> people can put themselves on the 'announcements' list, but I don't
> know how Dreamhost handles self-signup for announce lists.

Err…  I can't find the announcements list.  It doesn't seem to be
listed on lists.s-c.o.

**Comment by wking** [comment]
On Wed, Feb 27, 2013 at 05:58:35AM -0800, Greg Wilson wrote:

> Dreamhost manages announcement (broadcast) lists separately from
> discussion (Mailman) lists --- different part of their web-based
> control panel, different software behind the scenes.  Jon's got this
> one...

What sorts of things will be posted in the announcements list?  There
are so many lists already, and distinctions between them seem fuzzy to
me.  For example, I'd fold dev@ and gits@ into discuss@.  I'd also
probably fold planning@ into tutors@ (or vice versa), now that tutors@
is “only for low-volume discussion about scheduling and staffing of
upcoming boot camps”.  On the other hand, the dev@ and planning@
archives are private, so maybe I'm mis-characterizing their content
and purpose.

**Comment by pipitone** [comment]
Dreamhost (the swc webhost) tightly manages their announcement (one-way
broadcast) lists as a way to stop spammers.  To send mail you must submit
it through an online form on the dreamhost control panel.

**Comment by gvwilson** [comment]
1. 'announcements' is a broadcast-only list with almost 900 people on it 
   (past boot camp participants). Everyone gets a chance to sign up 
   immediately after a boot camp (it's opt-in).  We use it about once a 
   month (often less) for major announcements.
2. 'gits' and 'assessment' are going to be retired --- the first has 
   served its purpose, the second never really took off.
3. 'planning' will be retired.
4. 'dev' will remain as the small-circulation non-public list that every 
   project needs to have :-)
5. 'tutors' is now only used for matching people with teaching gigs.  No 
   reason the archives can't be public, but sign-up should require moderation.

**Comment by pipitone** [comment]
There is an opt-in mechanism, but we have to create it ourselves[1].  It
involves making a form that people can submit.

Jon.

[1]
http://wiki.dreamhost.com/Announcement_Mailing_List#How_can_people_subscribe_to_my_mailing_list.3F

**Comment by gvwilson** [comment]
_sigh_ OK, please ticket this separately --- we should.
- G

**Comment by wking** [comment]
Links to discuss@ and announcements@ were added with 8218f76398bcb3f9bc2bb32a9a110395c1e12bb8 merging #331.  Is that sufficient to close this PR?

**Comment by gvwilson** [comment]
Yup --- PR closed.
