### ISSUE TITLE
Boot camp at University of Chicago June 2013

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/DEPRECATED-website#319]
Dates are now set: June 17-18, 2013.

I am especially in need of instructor(s) comfortable with teaching the later advanced sections (debugging, testing, and documentation). My administrative contact at UChicago said they would definitely consider helping with travel costs as long as it wasn't too expensive (I wasn't given a figure), but to be safe we should probably limit it to instructors in the Midwest. Please let me know if you would like to help and which of these dates works for you. Thanks!

**Comment by stevemcgough** [comment]
I'm planning to be in Madison WI April 29th till May 3rd for a Software Carpentry bootcamp and HTCondor Week. I'll be travelling back through Chicago on the 4/5th so if you run it on the 6/7th I could hang around to help and probably do debugging / testing. As I've already got flights through the only thing I could do with would be accommodation.

cheers,

steve..

**Comment by rhiever** [comment]
Coming from MSU/East Lansing, I'm available for both dates.
- Randy Olson

**Comment by wltrimbl** [comment]
I can help out again; (firm commitment pending firm date) I'm local to the neighborhood containing the University of Chicago.

**Comment by jdblischak** [comment]
The scheduling for this event has unfortunately become more complicated because of a miscommunication between me and my administrative contact. I had asked for dates during the week, and she approved them assuming we would run the bootcamp in the evenings. This is because it is difficult to find a lecture hall that is open the entire day for two consecutive days when classes are in session. The situation is made even worse by the fact that the registrar has not yet released the room availabilities for Spring quarter, thus making it impossible to know if such a rare lecture hall was available on the dates I had previously proposed. 

Some alternative dates are:

May 4-5
June 17-20 (any two consecutive days)

The first is a weekend, so it would be easier to get a room. It also syncs with Steve's schedule. There are no classes during the week of June 17 because it is the break between Spring and Summer quarters. 

Please let me know what you think of these dates, and I apologize for the inconvenience.

Thanks!

**Comment by gvwilson** [comment]
No preference at this end --- please go ahead and pick whichever you 
think will work best.

**Comment by wltrimbl** [comment]
I can make either of the dates as well, with the exception of June 20.

**Comment by rhiever** [comment]
Same -- all dates work for me.


## 

Randal S. Olson

Computer Science PhD Student
Michigan State University
E-mail: rso@randalolson.com
http://www.randalolson.com

**Comment by jdblischak** [comment]
The official date is June 17-18.

**Comment by jdblischak** [comment]
Randy and Will, could you please confirm your commitment for June 17-18?

Steve, sorry about the date change. Please let me know you could help us out in June, but of course I understand if that is too much traveling for you.

**Comment by rhiever** [comment]
Yep, June 17-18 works for me. I'll be a short train ride away in East Lansing.

**Comment by wltrimbl** [comment]
Yes, I can commit to June 17-18, bootcamp in Chicago.

w

**Comment by stevemcgough** [comment]
Sorry,

I won't be in the states in June.

Steve..

Sent from my iPad

On 21 Mar 2013, at 13:47, "jdblischak" <notifications@github.com<mailto:notifications@github.com>> wrote:

Randy and Will, could you please confirm your commitment for June 17-18?

Steve, sorry about the date change. Please let me know you could help us out in June, but of course I understand if that is too much traveling for you.

**Comment by patrickfuller** [comment]
If need be, I'm willing to help out again (Sorry for the delay - I am waay behind on emails).

**Comment by jdblischak** [comment]
I'd like to have a sense of what everyone wants to teach so that I'll know if there are any holes in our instructor team. Could you please let me know which boot camp sections you are comfortable teaching? Please list them in order beginning with those you most want to teach at the top and those you would least like to teach at the bottom. I am currently planning on keeping the same sections we have previously taught a UChicago (Shell, Python variables and data structures, Python flow control and functions, Version control, Debugging, Testing, and Documentation), but of course I am open to suggestions for a different format. Thanks!
