### ISSUE TITLE
Boot camp for University of Southern California

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#320]
Ewa Deelman at isi.edu would like something (tentatively the week of Sept 16, 2013)

**Comment by jkitzes** [comment]
If this goes forward, I could hop down as an instructor if that's helpful.

**Comment by arokem** [comment]
Yes - me too.

**Comment by amyrhoda** [comment]
@jkitzes and @arokem, are you still up for this? We're starting to finalize the details. It will be Sep 16-17.

**Comment by jkitzes** [comment]
Turns out I have to bow out, unfortunately, as I'm teaching a course at UC Berkeley this fall and need to be around for class during the week.

**Comment by arokem** [comment]
Yes - I can make it. What's the plan?
