### ISSUE TITLE
Need a subscribe/unsubscribe page for announcements email list

### ISSUE THREAD

**Issue by amyrhoda** [swcarpentry/DEPRECATED-website#328]
See http://wiki.dreamhost.com/KB_/_Web_Programming_/_CGI%2C_PHP_%26_Databases_/_Announcement_Mailing_List#How_can_people_subscribe_to_my_mailing_list.3F

**Comment by wking** [comment]
Closed with 8218f76398bcb3f9bc2bb32a9a110395c1e12bb8 merging #331.
