### ISSUE TITLE
Stand-alone unsubscribe page

### ISSUE THREAD

**Issue by amyrhoda** [swcarpentry/DEPRECATED-website#338]
It would be great if we could have a stand-alone unsubscribe page for the announcement list, so we could include a "unsubscribe" link in mailouts. Ideally it would auto-populate with recipient's email address so they just have to click "unsubscribe".

Unsubscribing should send them to a page with links to our Twitter and Facebook so they can stay in touch other ways if they want to.

**Comment by pipitone** [comment]
@amyrbrown, I've put a bare bones unsubscribe page for you to look at here: http://dev.software-carpentry.org/about/unsubscribe.html. You can also hit the page with and email address in the URL, e.g. http://dev.software-carpentry.org/about/unsubscribe.html?email=example@example.com and the email auto-populates. I've checked and we can make that happen in the emails sent from DreamHost.  

I'm not sure where to redirect upon successfully removing them.  Boringly, I have it redirecting to the contributing page right now. Are you thinking we create a completely separate page that says something like, "We're sorry to see you go!  Here are other ways you can still stay in touch with us:... "?

**Comment by amyrhoda** [comment]
Yup, I think we should have a separate confirmation page after people have unsubscribed, if only to assure them that it worked.

**Comment by pipitone** [comment]
Whelp, there is now just a basic, bland "unsubscribe successful" page supplied by Dreamhost (our webhost) that comes up.  My sense is that it's good enough for the moment.
