### ISSUE TITLE
Write a "Perspectives" piece for a general science publication

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#350]
@npch suggested that we need a "Perspectives"-style piece published in a general science publication lamenting on the current state of software development skills in the research sector, suggesting how we got here, highlighting the bright spots that we've seen, and suggesting what might be the way forward for the next 5-10 years. He then volunteered to write it.

**Comment by npch** [comment]
I am getting @ahay from the Software Sustainability Institute's communications team to help me with this.

(tagging him so that he gets notifications)

**Comment by AHAY-zz** [comment]
Shall we have a virtual meeting soon to discuss this in detail?

**Comment by benwaugh** [comment]
Would someone like to set up a Doodle poll? I can, but perhaps someone more central (i.e. already named on this issue) could pre-select some times that suit them.

**Comment by npch** [comment]
I'm going to have a quick chat with @AHAY tomorrow about the mechanics of organising this, and then we'll put out a Doodle poll so that those who are interested in contributing can respond.
