### ISSUE TITLE
Write a reference paper for Software Carpentry

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#351]
Develop a specific "Software Carpentry" paper which we can use  when people ask to cite Software Carpentry. This would cover the teaching and evaluation techniques rather than the curriculum (which is the "Best Practices in Scientific Computing") paper.
- Where would this go? jCSCW? A specific ICT education journal?

**Comment by gvwilson** [comment]
Have started in https://github.com/swcarpentry/assets/tree/master/papers/software-carpentry-lessons-learned

**Comment by kcranston** [comment]
Great idea! Happy to help with this.

On Fri, Mar 15, 2013 at 12:50 PM, Greg Wilson notifications@github.comwrote:

> Have started in
> https://github.com/swcarpentry/assets/tree/master/papers/software-carpentry-lessons-learned
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/swcarpentry/website/issues/351#issuecomment-14971900
> .

## 

```
karen.cranston@gmail.com
@kcranstn
```
