### ISSUE TITLE
Boot camp for University of Iowa Sept 5-6, 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#353]
- Local host is Chris Schwarz
- Dates are September 5-6, 2013

**Comment by adina** [comment]
Old stomping ground of mine, interested if dates work out...will know more soon

**Comment by adina** [comment]
I can do this.

**Comment by amyrhoda** [comment]
Awesome, thanks @adina. Your co-instructor will be @JorySchossau and you'll be lead instructor.

**Comment by adina** [comment]
I'm happy to be co-instructors Jory.  :)  No need for me to be lead.  We'll touch base on this in the future.

-adina

**Comment by JorySchossau** [comment]
Hey Adina, sounds great! I'm gone the first 15 days of August so if we need
to organize announcements/registration etc. then we should meet up or email
before then.
- Jory

**Comment by adina** [comment]
@JorySchossau  I never have dealt with organizing registration.... @amyrbrown Do we need to come up with an announcement or is there one already being distributed?

**Comment by amyrhoda** [comment]
@adina and @JorySchossau, you don't need to handle announcements or registration -- I will do that.
