### ISSUE TITLE
Boot camp at Utah State University July 25-26, 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#356]

**Comment by ethanwhite** [comment]
I won't be here but I can definitely help provide contacts for qualified helpers / potential first time instructors.

**Comment by bendmorris** [comment]
Due to Pioneer Day, the dates of the CUAHSI conference have been changed. David has requested that we move the workshop to July 16-17.

**Comment by ethanwhite** [comment]
In that case I should still be around and would be happy to help teach.
