### ISSUE TITLE
Badge URLs don't work

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/DEPRECATED-website#361]
I was looking at my [super-duper SWC badge](http://beta.openbadges.org/share/a77a56b78294f0c174774c00fc37f5a5/) and the URLs associated with it have issues. The "Criteria" URL just goes to a list of created badges, and the "Evidence" link doesn't work at all.

**Comment by jiffyclub** [comment]
To be clear, the URLs that aren't working are links to software-carpentry.org.

**Comment by gvwilson** [comment]
Assigning to @pipitone --- Jon, have a look in bin/badge.py (which is more complicated than it ought to be) and I'll put together an email explaining where we are now.

**Comment by wking** [comment]
On Tue, Mar 12, 2013 at 10:56:14AM -0700, Greg Wilson wrote:

> Assigning to @pipitone --- Jon, have a look in bin/badge.py (which
> is more complicated than it ought to be)

I took a look at `badge.py` and the associated docs [1](https://github.com/mozilla/openbadges/wiki/Badge-Baking), which say:

  If you are building a new system, we strongly recommend using the
  JavaScript Issuer API for awarding badges. We will eventually either
  restrict or totally end the ability to award from the baking
  service.

**Comment by pipitone** [comment]
@gvwilson, @wking: Actually, we _can_ just use the Javascript Issuer API. See pipitone/website@7404f34a1a86fc01ff96a87419945ffa6dfb906e.

This means we don't need to "bake" the json assertions into images. The assertions can just refer to a single badge image for each kind of badge, and the javascript does the rest. If we go this route, folks get their badges by adding them to their Backpack.

Thoughts?

**Comment by jiffyclub** [comment]
@pipitone, that looks great!

**Comment by pipitone** [comment]
I've updated dev.software-carpentry.org/badges.  You should  be able to add your badge from there now (the assertion is coming from software-carpentry.org of course). 

@gvwilson This is basically a bake-on-demand service. The badge only comes into existence when someone adds it to their backpack. We just host the assertions and the unbaked badge images.
