### ISSUE TITLE
Boot camp at U. Pittsburgh

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#366]
- Host (Joshua Adelman) would prefer June 2013 if instructor(s) are available.
- See also #46.

**Comment by wking** [comment]
On Tue, Mar 12, 2013 at 05:55:32PM -0700, Greg Wilson wrote:

> Host (Joshua Adelman) would prefer June 2013 if instructor(s) are available.

I've got family in Pittsburgh, so I'm definitely interested ;).

**Comment by rachelslaybaugh** [comment]
I'd like to teach, I live in Pittsburgh and am an adjunct professor at Pitt.
