### ISSUE TITLE
Boot camp in Medellin, Colombia

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#368]
Juan Pineda from the supercomputing center at Universidad EAFIT contacted us to ask if we could run a boot camp for them.

**Comment by cozzini** [comment]
I can be part of the team: I was there a couple of time and it would be great to go back

**Comment by caitsydney** [comment]
Please.

**Comment by selik** [comment]
That'd be awesome.

**Comment by jaredlander** [comment]
Possibly, depending on when.

**Comment by gvwilson** [comment]
- Nathan Collier (@nocollier) is interested.

**Comment by amyrhoda** [comment]
It's looking like the Colombia boot camp will be in September. Please let me know if that still works for you.

**Comment by selik** [comment]
Should we know how to speak Spanish?
