### ISSUE TITLE
Arrange boot camp at Rockefeller University (New York)

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#385]
- Zachary Charlop-Powers (Laboratory of Genetically Encoded Small Molecules, Rockefeller U.) would like to host.

**Comment by adamobeng** [comment]
I'll help, if I'm around.

**Comment by zachcp** [comment]
Just checking in. I'm Zach Charlop-Powers and I'd like to host.

**Comment by matthewruttley** [comment]
Hi! I can help out. When are you intending to run the camp?

**Comment by zachcp** [comment]
I was thinking of targeting May or June but we wanted to see if there were local instructors available or if we need to try to fly someone in.

**Comment by matthewruttley** [comment]
May/June sounds good. There are quite a few of us here in NYC! It might be cool to fly in a python "celebrity" for a second session though :D

**Comment by zachcp** [comment]
@adamobeng @matthewguitar89 

Thanks for responding. I'm new to this so any help/advice you may have is welcome.  So my basic question is: can you guys run a bootcamp or do we need to keep looking?   I agree that bringing in a "celebrity" would be nice and I'm looking around for funding but I would like to start organizing. If we can get a few instructors lined up I can start   working on rooms/helpers/material etc.

I am thinking that I would like to target a PostDoc audience with some general computational knowledge along the lines of the LBNL description here:  http://software-carpentry.org/bootcamps/2013-03-lbl.html

**Comment by adamobeng** [comment]
There is a formal stratification between instructors and helpers and I am
but the latter.

@adamobeng https://github.com/adamobeng
@matthewguitar89https://github.com/matthewguitar89

Thanks for responding. I'm new to this so any help/advice you may have is
welcome. So my basic question is: can you guys run a bootcamp or do we need
to keep looking? I agree that bringing in a "celebrity" would be nice and
I'm looking around for funding but I would like to start organizing. If we
can get a few instructors lined up I can start working on
rooms/helpers/material etc.

I am thinking that I would like to target a PostDoc audience with some
general computational knowledge along the lines of the LBNL description
here: http://software-carpentry.org/bootcamps/2013-03-lbl.html

—
Reply to this email directly or view it on
GitHubhttps://github.com/swcarpentry/website/issues/385#issuecomment-15085227
.

**Comment by gvwilson** [comment]
Replaced by #497.
