### ISSUE TITLE
Create "check my machine" script for Mac OS X

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#39]
Write a small script that people can download from our web site and run on their machine that will tell them if everything they need for a boot camp has been installed correctly --- see https://github.com/swcarpentry/website/issues/38 for starting points.

**Comment by wking** [comment]
I just tested my “Linux” scripts on 10.6.8 and they work there too.  I
don't think we need different scripts for OS X.  If we get to the
point where we want to provide installation suggestions (instead of
just telling the user what they have installed), it will be easy
enough to switch on `os.name` to select the appropriate hint.

**Comment by gvwilson** [comment]
Agreed: should we use 'posix' and 'win32' as names (since that's what 
os.name returns)?
Thx,
G

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 06:47:19AM -0800, Greg Wilson wrote:

> Agreed: should we use 'posix' and 'win32' as names (since that's what 
> os.name returns)?

I'm fine with that, but we could also use `platform.system().lower()`
for marketing-style names [1](http://docs.python.org/2/library/platform.html#platform.system).

**Comment by gvwilson** [comment]
I'm good either way --- only difference is that Linux and Mac both 
report 'posix' for os.name.  Your call...

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 11:19:13AM -0800, Greg Wilson wrote:

> I'm good either way --- only difference is that Linux and Mac both 
> report 'posix' for os.name.  Your call...

Then if we want different instructions for Linux/Mac, we should
probably use `platform.system().lower()`.

**Comment by wking** [comment]
I'm closing this PR. Future feedback should go in swcarpentry/boot-camps#12, which currently has a fairly complete implementation.
