### ISSUE TITLE
Create "check my machine" script for Windows

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#40]
Write a small script that people can download from our web site and run on their machine that will tell them if everything they need for a boot camp has been installed correctly --- see https://github.com/swcarpentry/website/issues/38 for starting points.

**Comment by wking** [comment]
I expect my “Linux” script will work on MS Windows too, but I don't
have a Windows box available for testing.  Can someone with a Windows
box check the following and report back with the output:

  $ git clone -b installation-test --single-branch git://github.com/wking/swc-website.git
  $ cd swc-website
  $ python swc-installation-test-1.py
  Passed
  $ python swc-installation-test-2.py
  check virtual-shell...  pass
  check virtual-editor... pass
  check virtual-browser...        pass
  …

If something's broken, I can try and help fix them remotely, but it
would be nice if someone with some Windows and Python experience could
take the lead on compatibly patches.  I'll help keep you honest on the
POSIX side ;).

**Comment by ian-mitchell** [comment]
I'm running cygwin.  The current version of git in cygwin is 1.7.9, so I don't have the --single-branch option.  However, after removing that option, I was able to clone the whole repository and get the correct branch.

I've got EPD 7.3-2 installed (so I can run ipython and load scipy, numpy, etc), but I'm guessing that my cygwin installation (where I ran these test scripts) cannot see the EPD installation.

```
mitchell@armstrong ~/Workshops/SWCarpentry/CheckMyMachine
$ git clone -b installation-test git://github.com/wking/swc-website.git         
Cloning into 'swc-website'...
remote: Counting objects: 3401, done.
remote: Compressing objects: 100% (2529/2529), done.
remote: Total 3401 (delta 840), reused 3362 (delta 819)
Receiving objects: 100% (3401/3401), 57.17 MiB | 781 KiB/s, done.
Resolving deltas: 100% (840/840), done.

mitchell@armstrong ~/Workshops/SWCarpentry/CheckMyMachine
$ cd swc-website/

mitchell@armstrong ~/Workshops/SWCarpentry/CheckMyMachine/swc-website
$ python swc-installation-test-1.py
Passed

mitchell@armstrong ~/Workshops/SWCarpentry/CheckMyMachine/swc-website
$ python swc-installation-test-2.py
check virtual-shell...  pass
check virtual-editor... fail
check virtual-browser...        fail
check Git (git)...      pass
check Mercurial (hg)... pass
check Mercurial Python package (mercurial)...   pass
check make...   pass
check virtual-pypi-installer... fail
check Setuptools (setuptools)...        fail
check Nose (nosetests)...       pass
check Nose Python package (nose)...     fail
check SQLite 3 (sqlite3)...     fail
check SQLite Python package (sqlite3-python)... pass
check Python version (python)...        pass
check IPython...        fail
check NumPy (numpy)...  pass
check SciPy (scipy)...  fail
check Matplotlib (matplotlib)...        fail
check SymPy (sympy)...  fail
check Cython... fail
check NetworkX (networkx)...    fail
check MayaVi (mayavi.mlab)...   fail

Successes:

virtual-shell Bourne Again Shell (bash) 4.1.10
Git (git) 1.7.9
Mercurial (hg) 2.4.1
Mercurial Python package (mercurial) 2.3.1
make 3.82.90
Nose (nosetests) 1.1.2
SQLite Python package (sqlite3-python) 2.6.8 (unknown, Jun  9 2012, 11:30:32)
[GCC 4.5.3]
Python version (python) 2.6.8 (unknown, Jun  9 2012, 11:30:32)
[GCC 4.5.3]
NumPy (numpy) 1.6.2

Failures:

check for Notepad++ (notepad++) failed:
could not find 'notepad++.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Chromium (chromium) failed:
could not find 'chromium.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for pip failed:
could not find 'pip.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Setuptools (setuptools) failed:
could not import the 'setuptools' package for Setuptools (setuptools)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Nose Python package (nose) failed:
could not import the 'nose' package for Nose Python package (nose)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for SQLite 3 (sqlite3) failed:
could not find 'sqlite3.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for IPython failed:
could not import the 'IPython' package for IPython
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for SciPy (scipy) failed:
could not import the 'scipy' package for SciPy (scipy)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Matplotlib (matplotlib) failed:
could not import the 'matplotlib' package for Matplotlib (matplotlib)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for SymPy (sympy) failed:
could not import the 'sympy' package for SymPy (sympy)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Cython failed:
could not import the 'Cython' package for Cython
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for NetworkX (networkx) failed:
could not import the 'networkx' package for NetworkX (networkx)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for MayaVi (mayavi.mlab) failed:
could not import the 'mayavi.mlab' package for MayaVi (mayavi.mlab)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

If you do not understand why the above failures occurred,
copy and send the *entire* output (all info above and summary
below) to the instructor for help.

==================
System information
==================
os.name            : posix
os.uname           : ('CYGWIN_NT-6.1-WOW64', 'armstrong', '1.7.17(0.262/5/3)', '2012-10-19 14:39', 'i686', '')
platform           : cygwin
platform+          : CYGWIN_NT-6.1-WOW64-1.7.17-0.262-5-3-i686-32bit
prefix             : /usr
exec_prefix        : /usr
executable         : /usr/bin/python
version_info       : (2, 6, 8, 'final', 0)
version            : 2.6.8 (unknown, Jun  9 2012, 11:30:32)
[GCC 4.5.3]
environment        :
  !::=::\
  ALLUSERSPROFILE=C:\ProgramData
  APPDATA=C:\Users\mitchell\AppData\Roaming
  CLASSPATH=.;C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip
  COMMONPROGRAMFILES=C:\Program Files (x86)\Common Files
  COMPUTERNAME=ARMSTRONG
  COMSPEC=C:\Windows\system32\cmd.exe
  CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
  CommonProgramW6432=C:\Program Files\Common Files
  DFSTRACINGON=FALSE
  FP_NO_HOST_CHECK=NO
  HISTCONTROL=ignoreboth
  HISTIGNORE=[   ]*:&:bg:fg:exit
  HOME=/home/mitchell
  HOMEDRIVE=C:
  HOMEPATH=\Users\mitchell
  HOSTNAME=armstrong
  INFOPATH=/usr/local/info:/usr/share/info:/usr/info:
  LANG=en_US.UTF-8
  LOCALAPPDATA=C:\Users\mitchell\AppData\Local
  LOGONSERVER=\\ARMSTRONG
  MANPATH=/usr/local/man:/usr/share/man:/usr/man::/usr/ssl/man
  NUMBER_OF_PROCESSORS=2
  OLDPWD=/home/mitchell/Workshops/SWCarpentry/CheckMyMachine
  OS=Windows_NT
  PATH=/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Common Files/NetSarang:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Program Files (x86)/Common Files/Ulead Systems/MPEG:/cygdrive/c/PROGRA~2/COMMON~1/ULEADS~1/MPEG:/cygdrive/c/Program Files (x86)/Common Files/Lenovo:/cygdrive/c/Program Files/Common Files/Lenovo:/cygdrive/c/Program Files (x86)/Lenovo/Client Security Solution:/cygdrive/c/Program Files/Lenovo/Client Security Solution:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/90/Tools/binn:/cygdrive/c/Program Files/MATLAB/R2012a/bin:/cygdrive/c/Program Files/MATLAB/R2010b/bin:/cygdrive/c/Program Files/MATLAB/R2009a/bin:/cygdrive/c/Program Files/MATLAB/R2009a/bin/win64:/cygdrive/c/Program Files/gs/gs8.64/bin:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Microsoft Windows Performance Toolkit:/cygdrive/c/Program Files (x86)/MiKTeX 2.9/miktex/bin:/cygdrive/c/Program Files (x86)/QuickTime/QTSystem:/cygdrive/c/Program Files/TortoiseHg:/cygdrive/c/Program Files/TortoiseGit/bin:/cygdrive/c/Python27:/cygdrive/c/Python27/Scripts:/usr/lib/lapack
  PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  PRINTER=\\winserver.cs.ubc.ca\iccs-212
  PROCESSOR_ARCHITECTURE=x86
  PROCESSOR_ARCHITEW6432=AMD64
  PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 23 Stepping 10, GenuineIntel
  PROCESSOR_LEVEL=6
  PROCESSOR_REVISION=170a
  PROGRAMFILES=C:\Program Files (x86)
  PS1=\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$
  PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
  PUBLIC=C:\Users\Public
  PWD=/home/mitchell/Workshops/SWCarpentry/CheckMyMachine/swc-website
  ProgramData=C:\ProgramData
  ProgramFiles(x86)=C:\Program Files (x86)
  ProgramW6432=C:\Program Files
  QTJAVA=C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip
  RR=C:\Program Files (x86)\Lenovo\Rescue and Recovery
  SESSIONNAME=Console
  SHELL=/bin/bash
  SHLVL=1
  SWSHARE=C:\SWSHARE
  SYSTEMDRIVE=C:
  SYSTEMROOT=C:\Windows
  TEMP=/tmp
  TERM=xterm
  TMP=/tmp
  TPCCommon=C:\PROGRA~2\THINKV~1\PrdCtr
  TRACE_FORMAT_SEARCH_PATH=\\NTREL202.ntdev.corp.microsoft.com\34FB5F65-FFEB-4B61-BF0E-A6A76C450FAA\TraceFormat
  TSMPATH=C:\Program Files (x86)\ThinkPad\Tablet Shortcut
  TVT=C:\Program Files (x86)\Lenovo
  TVTCOMMON=C:\Program Files (x86)\Common Files\Lenovo
  TVTPYDIR=C:\Program Files (x86)\Common Files\Lenovo\Python24
  TZ=America/Vancouver
  USER=mitchell
  USERDOMAIN=armstrong
  USERNAME=mitchell
  USERPROFILE=C:\Users\mitchell
  VBOX_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
  VS100COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\
  WINDIR=C:\Windows
  _=/usr/bin/python
  asl.log=Destination=file;OnFirstLog=command,environment
  configsetroot=C:\Windows\ConfigSetRoot
  temp=C:\Users\mitchell\AppData\Local\Temp
  tmp=C:\Users\mitchell\AppData\Local\Temp
==================

For suggestions on installing missing packages, see
http://software-carpentry.org/setup/

For instructings on installing a particular package,
see the failure message for that package printed above.

For help, email the *entire* output of this script to
your instructor.

mitchell@armstrong ~/Workshops/SWCarpentry/CheckMyMachine/swc-website
$
```

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 09:47:28AM -0800, Ian M. Mitchell wrote:

> I'm running cygwin.

OK.

> The current version of git in cygwin is 1.7.9, so I don't have the
> --single-branch option.  However, after removing that option, I was
> able to clone the whole repository and get the correct branch.

No problem.  The only downside is that you're downloading ~300 M of
repository instead of ~132 K ;).

> I've got EPD 7.3-2 installed (so I can run ipython and load scipy,
> numpy, etc), but I'm guessing that my cygwin installation (where I
> ran these test scripts) cannot see the EPD installation.

Probably not.  And it looks like it can't see native Windows
executables either?

> Mercurial (hg) 2.4.1
> Mercurial Python package (mercurial) 2.3.1

This is very strange.  Do you really have a separate versions of
Mercurial for the executable and Python package?

> check for Notepad++ (notepad++) failed:
> could not find 'notepad++.exe' executable

This is the last failure from the virtual-editor check.  Do you have
any editors installed in the Cygwin environment?

> check for Chromium (chromium) failed:
> could not find 'chromium.exe' executable

Same as above, but for virtual-browser.  Any Cygwin browsers? :p.

Alternatively, any way to reach outside Cygwin an look for native
applications?

> check for Nose Python package (nose) failed:
> could not import the 'nose' package for Nose Python package (nose)
> For instructions on installing an up-to-date version, see
> http://software-carpentry.org/setup/

You have the nosetest executable, but not the nose Python package?
Weird, but we probably don't use it directly in SWC classes.  I just
included it in the default checks for completeness.

> check for SQLite 3 (sqlite3) failed:
> could not find 'sqlite3.exe' executable

Do you have this executable installed somewhere?

> check for IPython failed:
> could not import the 'IPython' package for IPython

Ditto.

> check for SciPy (scipy) failed:
> could not import the 'scipy' package for SciPy (scipy)
> …
> could not import the 'matplotlib' package for Matplotlib (matplotlib)
> …
> could not import the 'sympy' package for SymPy (sympy)
> …
> could not import the 'Cython' package for Cython
> …
> could not import the 'networkx' package for NetworkX (networkx)
> …
> could not import the 'mayavi.mlab' package for MayaVi (mayavi.mlab)

Are any of these Python packages actually installed?

**Comment by rmdickson** [comment]
Like Ian I'm working in Cygwin.  I had some packages not installed, and the script correctly failed those ones, and it correctly found a bunch of others.  I'll omit that verbiage.  The two weirdnesses were Mercurial and nosetests:

$ which nosetests hg
/usr/bin/nosetests
/usr/bin/hg

$ hg --version
Mercurial Distributed SCM (version 2.3.1) ...

$ nosetests --version
nosetests version 1.1.2

$ python swc-installation-test-2.py hg mercurial nosetests
check Mercurial (hg)... fail
check Mercurial Python package (mercurial)...   pass
check Nose (nosetests)...       fail

Successes:

Mercurial Python package (mercurial) 2.3.1

Failures:

check for Mercurial (hg) failed:
outdated version of Mercurial (hg): 1.8.3 (need >= 2.0.0)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Nose (nosetests) failed:
could not find 'nosetests.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

If you do not understand why the above failures occurred,
copy and send the _entire_ output (all info above and summary
below) to the instructor for help.

# 

# System information

os.name            : posix
os.uname           : ('CYGWIN_NT-6.1-WOW64', 'ross-r700', '1.7.17(0.262/5/3)', '2012-10-19 14:39', 'i686', '')
platform           : cygwin
platform+          : CYGWIN_NT-6.1-WOW64-1.7.17-0.262-5-3-i686-32bit
prefix             : /usr
exec_prefix        : /usr
executable         : /usr/bin/python
version_info       : (2, 6, 8, 'final', 0)
version            : 2.6.8 (unknown, Jun  9 2012, 11:30:32)
[GCC 4.5.3]
environment        :
  !::=::\
  ALLUSERSPROFILE=C:\ProgramData
  APPDATA=C:\Users\ross\AppData\Roaming
  CLASSPATH=.;C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip
  COMMONPROGRAMFILES=C:\Program Files (x86)\Common Files
  COMPUTERNAME=ROSS-R700
  COMSPEC=C:\windows\system32\cmd.exe
  CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
  CommonProgramW6432=C:\Program Files\Common Files
  DEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection
  FP_NO_HOST_CHECK=NO
  HOME=/home/ross
  HOMEDRIVE=C:
  HOMEPATH=\Users\ross
  HOSTNAME=ross-r700
  INFOPATH=/usr/local/info:/usr/share/info:/usr/info:
  LANG=en_US.UTF-8
  LOCALAPPDATA=C:\Users\ross\AppData\Local
  LOGONSERVER=\ROSS-R700
  MANPATH=/usr/local/man:/usr/share/man:/usr/man:
  NUMBER_OF_PROCESSORS=4
  OLDPWD=/home/ross/test-setup
  OS=Windows_NT
  PATH=/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Common Files/Microsoft Shared/Windows Live:/cygdrive/c/Program Files (x86)/Common Files/Microsoft Shared/Windows Live:/cygdrive/c/windows/system32:/cygdrive/c/windows:/cygdrive/c/windows/System32/Wbem:/cygdrive/c/windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Windows Live/Shared:/cygdrive/c/Program Files/TortoiseHg:/cygdrive/c/Program Files/TortoiseSVN/bin:/cygdrive/c/Program Files (x86)/QuickTime/QTSystem:/cygdrive/c/Program Files/MATLAB/R2010bSP2/bin:/usr/lib/lapack:.
  PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
  PRINTER=HP LaserJet M3027 mfp PCL6
  PROCESSOR_ARCHITECTURE=x86
  PROCESSOR_ARCHITEW6432=AMD64
  PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 37 Stepping 5, GenuineIntel
  PROCESSOR_LEVEL=6
  PROCESSOR_REVISION=2505
  PROGRAMFILES=C:\Program Files (x86)
  PS1=[\e]0;\w\a]\n[\e[32m]\u@\h [\e[33m]\w[\e[0m]\n\$
  PSModulePath=C:\windows\system32\WindowsPowerShell\v1.0\Modules\
  PUBLIC=C:\Users\Public
  PWD=/home/ross/test-setup/swc-website
  ProgramData=C:\ProgramData
  ProgramFiles(x86)=C:\Program Files (x86)
  ProgramW6432=C:\Program Files
  QTJAVA=C:\Program Files (x86)\Java\jre7\lib\ext\QTJava.zip
  SESSIONNAME=Console
  SHELL=/bin/bash
  SHLVL=1
  SYSTEMDRIVE=C:
  SYSTEMROOT=C:\windows
  TEMP=/tmp
  TERM=xterm
  TMP=/tmp
  TZ=America/Halifax
  USER=ross
  USERDOMAIN=ross-r700
  USERNAME=ross
  USERPROFILE=C:\Users\ross
  VBOX_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
  VSEDEFLOGDIR=C:\ProgramData\McAfee\DesktopProtection
  WINDIR=C:\windows
  YPCAGADGET=TOSHIBA
  _=/usr/bin/python
  temp=C:\Users\ross\AppData\Local\Temp

#   tmp=C:\Users\ross\AppData\Local\Temp

For suggestions on installing missing packages, see
http://software-carpentry.org/setup/

For instructings on installing a particular package,
see the failure message for that package printed above.

For help, email the _entire_ output of this script to
your instructor.

**Comment by rmdickson** [comment]
Eh... Markdown.  Forgot about that.  Oh well.

**Comment by ian-mitchell** [comment]
On Thu, 3 Jan 2013, W. Trevor King wrote:

> On Thu, Jan 03, 2013 at 09:47:28AM -0800, Ian M. Mitchell wrote:
> 
> > I've got EPD 7.3-2 installed (so I can run ipython and load scipy,
> > numpy, etc), but I'm guessing that my cygwin installation (where I
> > ran these test scripts) cannot see the EPD installation.
> 
> Probably not. And it looks like it can't see native Windows
> executables either?

Most of those native Windows executables are probably not on the path. 
Since Windows installers spread the binaries / batch files all over 
the place, I haven't bothered to add them to the path (or create 
shortcuts) except for those few that I start from the cygwin prompt.

My guess is that most Windows users (and certainly fresh cygwin 
installs) would be in a similar situation.  We just start native apps 
from the "start" menu.

> > Mercurial (hg) 2.4.1
> > Mercurial Python package (mercurial) 2.3.1
> 
> This is very strange. Do you really have a separate versions of
> Mercurial for the executable and Python package?

That is strange.  Look at this:

```
mitchell@armstrong ~/Workshops/SWCarpentry/CheckMyMachine/swc-website
$ hg --version
Mercurial Distributed SCM (version 2.3.1)
(see http://mercurial.selenic.com for more information)
```

How does the script detect the hg version number?

> > check for Notepad++ (notepad++) failed:
> > could not find 'notepad++.exe' executable
> 
> This is the last failure from the virtual-editor check. Do you have
> any editors installed in the Cygwin environment?

Lots of editors, but none on the cygwin path.  Easily fixed with a 
fresh install of cygwin that included nano.

> > check for Chromium (chromium) failed:
> > could not find 'chromium.exe' executable
> 
> Same as above, but for virtual-browser. Any Cygwin browsers? :p.

Cygwin has lynx, but no graphical browsers to my knowledge.  Failure 
to access my firefox installation is probably related to the path 
problem.

> Alternatively, any way to reach outside Cygwin an look for native
> applications?

Not that I know of, but I'm no expert.  I just know where to click.

> > check for Nose Python package (nose) failed: could not import the 
> > 'nose' package for Nose Python package (nose) For instructions on 
> > installing an up-to-date version, see 
> > http://software-carpentry.org/setup/
> 
> You have the nosetest executable, but not the nose Python package?
> Weird, but we probably don't use it directly in SWC classes. I just
> included it in the default checks for completeness.
> 
> > check for SQLite 3 (sqlite3) failed:
> > could not find 'sqlite3.exe' executable
> 
> Do you have this executable installed somewhere?

No I don't, so this failure is no surprise.

> > check for IPython failed:
> > could not import the 'IPython' package for IPython
> 
> Ditto.

IPython is available through my EPD installation.  I normally start it 
as pylab from the "start" menu.

I can also start it from the windows command prompt.  I'm not sure why 
it is visible to the windows command prompt, but not cygwin.

> > check for SciPy (scipy) failed:
> > could not import the 'scipy' package for SciPy (scipy)
> > …
> > could not import the 'matplotlib' package for Matplotlib (matplotlib)
> > …
> > could not import the 'sympy' package for SymPy (sympy)
> > …
> > could not import the 'Cython' package for Cython
> > …
> > could not import the 'networkx' package for NetworkX (networkx)
> > …
> > could not import the 'mayavi.mlab' package for MayaVi (mayavi.mlab)
> 
> Are any of these Python packages actually installed?

All installed through EPD.  When I start pylab (or run python or 
ipython from the windows command prompt) I can import them.

My success at running ipython from the windows command prompt lead me 
to try running the installation tester from there as well.

Not surprisingly git won't work on my machine because I've only 
installed git through cygwin; I assume that could be fixed with a 
regular git install.

Here is the result of running the installation tests:

```
c:\cygwin\home\mitchell\Workshops\SWCarpentry\CheckMyMachine\swc-website>python
swc-installation-test-1.py
Passed

c:\cygwin\home\mitchell\Workshops\SWCarpentry\CheckMyMachine\swc-website>python
swc-installation-test-2.py
check virtual-shell...  Traceback (most recent call last):
   File "swc-installation-test-2.py", line 599, in <module>
     passed = check(_sys.argv[1:])
   File "swc-installation-test-2.py", line 136, in check
     version = checker.check()
   File "swc-installation-test-2.py", line 190, in check
     self._check_dependencies()
   File "swc-installation-test-2.py", line 206, in _check_dependencies
     version = dependency.check()
   File "swc-installation-test-2.py", line 191, in check
     return self._check()
   File "swc-installation-test-2.py", line 219, in _check
     version = self._get_version()
   File "swc-installation-test-2.py", line 325, in _get_version
     version_stream = self._get_version_stream()
   File "swc-installation-test-2.py", line 299, in _get_version_stream
     close_fds=True, shell=False, universal_newlines=True)
   File "C:\Python27\lib\subprocess.py", line 637, in __init__
     raise ValueError("close_fds is not supported on Windows "
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```

I'm not sure that running from the windows command prompt is a 
solution even if the bug above were fixed.  Although I can run notepad 
from there, I can't run firefox (probably another path problem).

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 11:03:42AM -0800, Ross Dickson wrote:

> $ hg --version
> Mercurial Distributed SCM (version 2.3.1) ...
> …
> $ python swc-installation-test-2.py hg mercurial nosetests
> …
> Mercurial Python package (mercurial) 2.3.1

This looks good.

> check for Mercurial (hg) failed:
> outdated version of Mercurial (hg): 1.8.3 (need >= 2.0.0)

This is odd.  What do you get with `which hg.exe`?

Maybe we should be emptying CommandDependency.exe_extension on Cygwin?

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 11:05:06AM -0800, Ian M. Mitchell wrote:

> How does the script detect the hg version number?

For most commands (including `hg`), it runs (in
`CommandDependency._get_version_stream`):

  COMMAND --version

To find `COMMAND`, it takes the basic command name (e.g. `hg`) and
appends `CommandDependency.exe_extension` (e.g. `.exe`).  I set up
`exe_extension` using:

  distutils.ccompiler.new_compiler().exe_extension

but maybe that's the wrong approach…

> > This is the last failure from the virtual-editor check. Do you have
> > any editors installed in the Cygwin environment?
> 
> Lots of editors, but none on the cygwin path.  Easily fixed with a 
> fresh install of cygwin that included nano.

Should we suggest this, or find some way to detect native apps?

> ValueError: close_fds is not supported on Windows platforms if you
> redirect stdin/stdout/stderr

I've just weakened that constraint.  Hopefully the sub-commands don't
mess with any other descriptors ;).

> I'm not sure that running from the windows command prompt is a
> solution even if the bug above were fixed.  Although I can run
> notepad from there, I can't run firefox (probably another path
> problem).

If we can't rely on a `PATH` environment variable, we can probably
extend it internally with commonly used values to find commonly
installed software.  I imagine most MS Windows users have Firefox in
the same place, even if it's not in their `PATH`.

**Comment by ian-mitchell** [comment]
On Thu, 3 Jan 2013, W. Trevor King wrote:

> On Thu, Jan 03, 2013 at 11:05:06AM -0800, Ian M. Mitchell wrote:
> 
> > How does the script detect the hg version number?
> 
> For most commands (including `hg`), it runs (in
> `CommandDependency._get_version_stream`):
> 
> COMMAND --version
> 
> To find `COMMAND`, it takes the basic command name (e.g. `hg`) and
> appends `CommandDependency.exe_extension` (e.g. `.exe`). I set up
> `exe_extension` using:
> 
> distutils.ccompiler.new_compiler().exe_extension
> 
> but maybe that's the wrong approach…

Okay, that explains it.  By appending '.exe' the script gets my 
TortoiseHg version of mercurial:

mitchell@armstrong ~/Workshops/SWCarpentry/CheckMyMachine/swc-website
$ where hg
C:\cygwin\bin\hg
C:\Program Files\TortoiseHg\hg.exe

> > > This is the last failure from the virtual-editor check. Do you have
> > > any editors installed in the Cygwin environment?
> > 
> > Lots of editors, but none on the cygwin path. Easily fixed with a
> > fresh install of cygwin that included nano.
> 
> Should we suggest this, or find some way to detect native apps?

The former in the setup instructions, the latter in the test scripts.

> > ValueError: close_fds is not supported on Windows platforms if you
> > redirect stdin/stdout/stderr
> 
> I've just weakened that constraint. Hopefully the sub-commands don't
> mess with any other descriptors ;).

After pulling the modified test script, here is the relevant output 
from running it in my windows command prompt:

```
C:\cygwin\home\mitchell\Workshops\SWCarpentry\CheckMyMachine\swc-website>python swc-installation-test-2.py
check virtual-shell...  fail
check virtual-editor... fail
check virtual-browser...        fail
check Git (git)...      fail
check Mercurial (hg)... pass
check Mercurial Python package (mercurial)...   fail
check make...   fail
check virtual-pypi-installer... fail
check Setuptools (setuptools)...        pass
check Nose (nosetests)...       pass
check Nose Python package (nose)...     pass
check SQLite 3 (sqlite3)...     fail
check SQLite Python package (sqlite3-python)... pass
check Python version (python)...        pass
check IPython...        pass
check NumPy (numpy)...  pass
check SciPy (scipy)...  pass
check Matplotlib (matplotlib)...        pass
check SymPy (sympy)...  pass
check Cython... pass
check NetworkX (networkx)...    pass
check MayaVi (mayavi.mlab)...   pass

Successes:

Mercurial (hg) 2.4.1
Setuptools (setuptools) 0.6
Nose (nosetests) 1.1.2
Nose Python package (nose) 1.1.2
SQLite Python package (sqlite3-python) 2.7.3 |EPD 7.3-2 (64-bit)| 
(default, Apr
12 2012, 15:20:16) [MSC v.1500 64 bit (AMD64)]
Python version (python) 2.7.3 |EPD 7.3-2 (64-bit)| (default, Apr 12 
2012, 15:20:
16) [MSC v.1500 64 bit (AMD64)]
IPython 0.13
NumPy (numpy) 1.6.1
SciPy (scipy) 0.10.1
Matplotlib (matplotlib) 1.1.0
SymPy (sympy) 0.7.1
Cython 0.16
NetworkX (networkx) 1.6
MayaVi (mayavi.mlab) unknown

Failures:

check for Bourne Shell (sh) failed:
could not find 'sh.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Notepad++ (notepad++) failed:
could not find 'notepad++.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Chromium (chromium) failed:
could not find 'chromium.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Git (git) failed:
could not find 'git.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for Mercurial Python package (mercurial) failed:
could not import the 'mercurial.version' package for Mercurial Python package (mercurial)
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for make failed:
could not find 'make.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for pip failed:
could not find 'pip.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/

check for SQLite 3 (sqlite3) failed:
could not find 'sqlite3.exe' executable
For instructions on installing an up-to-date version, see
http://software-carpentry.org/setup/
```

The failures of sh, notepad++, chromium, git, make, pip and sqlite3 
are expected, since I do not have those installed in Windows.  I don't 
know whether sh, make, pip or sqlite3 are available in a version which 
will run from the command prompt.

I have no idea why the mercurial python package failed.  Maybe it is 
not part of EPD?

> > I'm not sure that running from the windows command prompt is a
> > solution even if the bug above were fixed. Although I can run
> > notepad from there, I can't run firefox (probably another path
> > problem).
> 
> If we can't rely on a `PATH` environment variable, we can probably
> extend it internally with commonly used values to find commonly
> installed software. I imagine most MS Windows users have Firefox in
> the same place, even if it's not in their `PATH`.

Probably.

**Comment by wking** [comment]
On Thu, Jan 03, 2013 at 11:48:06AM -0800, Ian M. Mitchell wrote:

> Okay, that explains it.  By appending '.exe' the script gets my 
> TortoiseHg version of mercurial:

Should I check with and without exe_extension and take the maximal
version?  Should I check only without exe_extension on Cygwin?  Should
we just try and set our minimum versions as low as possible and stick
to only testing the exe_extension location?

> > > Lots of editors, but none on the cygwin path. Easily fixed with a
> > > fresh install of cygwin that included nano.
> > 
> > Should we suggest this, or find some way to detect native apps?
> 
> The former in the setup instructions, the latter in the test scripts.

OK.  This means MS Windows users need to start sending me PATH
suggestions ;).  Where does Firefox live for you?  Where does Emacs
live for you?  Where does notepad++ live for you?…

> I have no idea why the mercurial python package failed.  Maybe it is 
> not part of EPD?

It is not:
http://www.enthought.com/products/epdlibraries-past.php?ver=7.3

I'll probably comment out the 'mercurial' check (in `CHECKS`) before
this gets merged, since I don't expect it to be used in a SWC course.

**Comment by ethanwhite** [comment]
This works perfectly on Windows 7 using GitBash (http://msysgit.github.com/) with EPD. GitBash uses the native Windows path so it sees all of the installed programs.The one thing that is missing is `make`, which is apparently not installed with GitBash, but since we don't typically use `make` in workshops that shouldn't be a problem.

**Comment by wking** [comment]
I'm closing this PR. Future feedback should go in swcarpentry/boot-camps#12, which currently has a fairly complete implementation.
