### ISSUE TITLE
data@ and assessment@ archives are currently private

### ISSUE THREAD

**Issue by wking** [swcarpentry/DEPRECATED-website#407]
From #405:

On Wed, Mar 20, 2013 at 07:21:03AM -0700, Greg Wilson wrote:

> On 2013-03-20 9:04 AM, W. Trevor King wrote:
> 
> > … Other than that, it looks good (although the data@ and
> > assessment@ archives are currently private).
> 
> … file a ticket against Amy to make the data and assessment archives public.

**Comment by gvwilson** [comment]
@pipitone to check, and then add links?
