### ISSUE TITLE
Boot camp at Duke University

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#41]
- R rather than Python
- Friday and Saturday in February or March 2013, excluding the first Friday of each month

**Comment by jaredlander** [comment]
I might be available depending on the exact date.

**Comment by emhart** [comment]
I could help.  I could do anything but early feb when Ethan is here and I'm busy from March 23rd on.

**Comment by emhart** [comment]
I'm still good if we do it in March...

**Comment by gvwilson** [comment]
- @emhart and @adamsonj will teach
