### ISSUE TITLE
Boot camp in Adelaide Sept 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#419]
The Australian Bioinformatics Network (ABN) has funding to bring one instructor to Australia from overseas to help teach a boot camp in Adelaide Sept 24-26, and another in Brisbane the following week (beginning Sept 30). If you're interested, please add your name to this ticket.  They'd strongly prefer someone with a bioinformatics background.
- See #472 for Brisbane boot camp
- See #473 for Canberra boot camp
- See #474 for Sydney boot camp
- See #475 for Melbourne boot camp

**Comment by karthik** [comment]
I'll throw my name in. (on further thought, I am not a traditional bioinformatician so someone else might be better suited).
