### ISSUE TITLE
Boot camp at Beacons Satellite Symposium, Bath - 15-16/07/13

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#42]
- Where: [Beacons Satellite Symposium](http://people.bath.ac.uk/ee3jarr/beaconsatellite2013/), Bath
- Host: Alex Chartier 
- Audience: attendees at the above
- Instructors: Mike Jackson, Chris Woods (@chryswoods)
- Helpers: Eliot Marsden, Fergus Cullen, Jeremy Metz, David Martin?, 
- Web site: http://software-carpentry.org/bootcamps/2013-07-bath.html
- Registration: Restricted
- Mailing list: http://lists.software-carpentry.org/listinfo.cgi/bath-software-carpentry.org
- Repository: https://github.com/swcarpentry/boot-camps/tree/2013-07-bath

**Comment by mikej888** [comment]
I can be one of the instructors.

**Comment by LJWilliams** [comment]
I would love to, but it is probably to $$$$ to go overseas

**Comment by mikej888** [comment]
@LJWilliams, sorry yes, I don't think Alex can cover the cost of flying an instructor over so we'll be going local.

**Comment by mikej888** [comment]
Asked Alex on status of seeking a room and machines at the conference, whether it seems this will go ahead, how he'd envisaged handling registration (offered EventBrite) and to confirm dates.

**Comment by mikej888** [comment]
Alex: It appears we can get the software installed on there, but that hasn't actually happened yet. My contact in IT Support is having a meeting about this in the next few days. In any case, we will find somewhere to run the course. 

We will proceed with the course. I would be happy to use EventBrite to handle the registration. I plan to give priority to a group of students that will be attending the Beacons conference in Bath the week before the boot camp, but I would be happy to let extra spaces go to the public.

**Comment by davidmam** [comment]
Why are all the UK boot camps next to my relatives? Possible, and as I may be on holiday down there (Trowbridge) at the time, very cheap too.. (I'll have to recuse myself from the other boot camps though). 
Edit: If we are in the area, I'll definitely offer to come along as a helper to see how these run.

**Comment by mikej888** [comment]
Chris Woods, Bristol, volunteered as an instructor.

**Comment by mikej888** [comment]
Dhavide Aruliah from Canada, may be able to instruct/help if times permit.

**Comment by mikej888** [comment]
Jeremy Metz, University of Exeter, may attend as helper.

**Comment by eddiejessup** [comment]
Elliot Marsden, University of Edinburgh, I'm happy to attend as a helper

**Comment by fcullen** [comment]
Fergus Cullen, University of Edinburgh, can attend as a helper

**Comment by davidmam** [comment]
As I said upthread, I may be nearby and will then come along as a helper.

**Comment by mikej888** [comment]
Dhavide can't make it.

**Comment by mikej888** [comment]
Alex and I think we should have a telcon on WB20/05 to discuss the timetable and who does what. Chris (@chryswoods), please could you fill in the Doodle poll (http://www.doodle.com/wkeg9p4dgwnensfp).

@eddiejessup, @fcullen, @davidmam, you are welcome to attend too if you are still planning to attend as helpers. Please confirm this either way, thanks.

**Comment by fcullen** [comment]
Just to confirm, I'm still keen to help out. Do we also need to attend the telecon?

**Comment by davidmam** [comment]
family issues may make my attendance - nothing serious but my mother in law who lives near Bath and with whom I would stay may be moving house to somewhere nowhere near Bath.

**Comment by eddiejessup** [comment]
I'm also happy to help out, let me know if there's anything I need to sort
out.

**Comment by mikej888** [comment]
@eddiejessup, @fcullen, @davidmam, thanks for the updates. Attending the telcon is optional.

**Comment by mikej888** [comment]
@fcullen, please could you send your e-mail address to host-bath@software-carpentry.org, thanks.
@eddiejessup, @fcullen, @davidmam, @fcullen - we've held our telcon and come up with the timetable and will add materials to the repository in due course. The link to the repo. is at the top of this issue ticket. I'll subscribe you to the mailing list for the boot camp.
