### ISSUE TITLE
Make the HOWTO easier to navigate by adding collapseable sections

### ISSUE THREAD

**Issue by pipitone** [swcarpentry/DEPRECATED-website#434]
> 29/03/13 12:27, Neil Chue Hong (SSI) wrote:
> Ideally, I'd suggest you do the fancy HTML5 roll-up of sections that Wikipedia
> uses, but I'm not creating a pull-request as I don't know how to do that sort of
> webpage wizardry :-)

Bootstrap has this feature, called "collapse": 
http://twitter.github.com/bootstrap/javascript.html#collapse

**Comment by jiffyclub** [comment]
The "Affix" navigation helper is pretty nice too. I find it a bit nicer for jumping around the document than expanding/collapsing sections.

**Comment by pipitone** [comment]
Oh yeah, good call!
