### ISSUE TITLE
Develop "for complete beginners" version of course

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#45]
We have a lot of requests from biologists, geographers, and others for an entry-level version of this course.

**Comment by ctb** [comment]
On Tue, Dec 11, 2012 at 06:42:42AM -0800, Greg Wilson wrote:

> We have a lot of requests from biologists, geographers, and others for an entry-level version of this course.

I think this is what the NSF OCI supplement that I got can be used for.
Sound good?

## 

C. Titus Brown, ctb@msu.edu

**Comment by gvwilson** [comment]
We're unlikely to get to this.
