### ISSUE TITLE
Add Stefano Cozzini to about/team.html

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#451]

**Comment by ahmadia** [comment]
The link to @cozzini 's page is broken from: http://software-carpentry.org/about/team.html

The URL it could link to: http://www.democritos.it/~cozzini.html

Is also broken...

The correct link is: http://www.democritos.it/~cozzini/

**Comment by gvwilson** [comment]
Fixed --- thanks.
