### ISSUE TITLE
Boot camp in Brisbane Sept 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#472]
The Australian Bioinformatics Network (ABN) has funding to bring one instructor to Australia from overseas to help teach a boot camp in Adelaide Sept 24-26, and another in Brisbane the following week (beginning Sept 30). If you're interested, please add your name to this ticket. They'd strongly prefer someone with a bioinformatics background.
- See #419 for Adelaide boot camp
- See #473 for Canberra boot camp
- See #474 for Sydney boot camp
- See #475 for Melbourne boot camp

**Comment by philippbayer** [comment]
Hi! I've already been in contact with Nathan about the Brisbane boot camp, and I've contacted UQ to get a room for about 40 participants. I've also talked to a couple of people at UQ, there's definitely interest in a) helping out and b) attending.

Getting a room at UQ is a bit messy as different parties are responsible for different buildings, I've contacted the right people twice but they haven't responded yet.
