### ISSUE TITLE
Run boot camp in Sydney

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#474]
Organize and run a boot camp in Sydney in the second half of 2013.
- See #419 for Adelaide boot camp
- See #472 for Brisbane boot camp
- See #473 for Canberra boot camp
- See #475 for Melbourne boot camp

**Comment by naught101** [comment]
I'm available to help.

**Comment by andrewletten** [comment]
Aiming for an R-based boot camp at UNSW at the end of the year (November/December) led by Rich and Daniel from Macquarie Uni - primarily targeting ecologists/evolutionary biologists but of course open to anyone interested...

**Comment by dbarneche** [comment]
I'm more than glad to help Rich and Daniel

**Comment by richfitz** [comment]
I should put my name in here too. Available to help, dates unclear at this point, but I don't have any major blocked out bits of time in the second half of 2013.
