### ISSUE TITLE
Run boot camp "highlights" at EGI Forum, Manchester - 11/04/13

### ISSUE THREAD

**Issue by mikej888** [swcarpentry/DEPRECATED-website#48]
- Where: Manchester
- Host: Michel Drescher 
- Audience: EGI Forum attendees 
- Instructors: Mike
- Helpers: Björn Hagemeier and SSI folks.
- Web site: http://software-carpentry.org/bootcamps/2013-04-egi-forum.html
- Registration: http://cf2013.egi.eu/registration/. Can check a forum registration box to express interest or drop-in on the day.
- Mailing list: N/A
- Repository: https://github.com/swcarpentry/boot-camps/tree/2013-04-egi-forum
- Syllabus: see repository README.md.

Early publicity:

http://www.egi.eu/news-and-media/newsfeed/news_0178_software_carpentry_workshop.html
http://www.egi.eu/blog/2012/11/08/software_carpentry_or_the_art_of_software_artisanship.html

Notes: Will set up VM at EPCC with temporary accounts so attendees can drop in if desired.

**Comment by drj11** [comment]
Mike, is this the same as issue #24? (where I already volunteered for shell).

**Comment by gvwilson** [comment]
Nope: the EGI workshop in Manchester is different from the general U. Manchester workshop.

**Comment by mikej888** [comment]
Proposed, for sessions,
-Version control (provenance) and Git
-Testing (correctness) 
and one of
-Advanced shell (find, awk,...) and Make (automation)
-Data management using files / or relational databases

Will set up VM at EPCC with temporary accounts so attendees can drop in if desired. 

Awaiting confirmation of:
-Proposed sessions above.
-Funding for instructors and helpers. If this is possible, I'll put out a mail for people interested in getting first-time instructor experience.
-Whether Manchester helpers could attend just for the sessions without paying registration and get experience for the following week's boot camp (#24)
-Names of local helpers.
-Room size and or whether adopting a first-come-first-served model on the day is OK.

**Comment by mikej888** [comment]
Sessions will be: version control, testing, data management using files and NoSQL.
No funding for 2nd instructor.
First-come first-served model is OK.

**Comment by mikej888** [comment]
Done and blogged,
- [SSI](http://www.software.ac.uk/blog/2013-04-16-software-carpentry-highlights-egi-forum)
- [EPCC](http://www.epcc.ed.ac.uk/blog/2013/04/16/software-carpentry-highlights-egi-forum)
- [SWC](http://software-carpentry.org/blog/2013/04/egi-forum.html)
