### ISSUE TITLE
Rename 'ubc' mailing list to 'bc'

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#484]
Now that people in Victoria and at SFU are interested in boot camps, we should rename the 'ubc' list to signal that it's for everyone in southwestern BC.

**Comment by amyrhoda** [comment]
I think so. It's usually best to keep terminology accurate rather than rely on folk knowledge, even if changing it is painful.

**Comment by amyrhoda** [comment]
Done, finally.
