### ISSUE TITLE
Boot camp for University of Edinburgh geosciences

### ISSUE THREAD

**Issue by mikej888** [swcarpentry/DEPRECATED-website#49]
In conjunction with Mike Mineter who attended the PRACE Edinburgh boot camp in December 2012. Mike said he'd be in touch with mikej888 in due course.

**Comment by drj11** [comment]
I'd like to help with this if possible.  teaching or being a helper.

**Comment by mikej888** [comment]
Closing boot camps which have no date. These tentative prospects are tracked in the Software Carpentry administrator Subversion repository. Have recorded your interest there @drj11.
