### ISSUE TITLE
Boot camp(s) in New York in September 2013

### ISSUE THREAD

**Issue by amyrhoda** [swcarpentry/DEPRECATED-website#497]
Double-header: Python and R. Who's in?

**Comment by acviana** [comment]
Interested.

**Comment by dwf** [comment]
Really enjoyed teaching the last NYC workshop, interested if it's towards the end of the month (after, say, the 20th). Can't make it before that, unfortunately. Also, don't really know my way around R, so I'd probably want to stick to Python.

**Comment by rhiever** [comment]
Coming from Michigan State University. I'd be happy to teach in the Python portion of the boot camp.

**Comment by BernhardKonrad** [comment]
Interested, and would be happy to help with R. But in Vancouver I'm far away...

**Comment by lauratboyer** [comment]
Interested for the R section -- I am based in Vancouver like Bernhard. There's a small chance I will be in Montreal at the end of August, so we might be able to figure something out.

**Comment by matthewruttley** [comment]
Interested in the Python bit :D

**Comment by adamobeng** [comment]
I'm about, I might be able to assist depending on timing.

Are these targeted at a specific audience?

**Comment by six5532one** [comment]
I'm based in NYC and can help with python. Will be helping at WiSE Boston before that!

**Comment by gvwilson** [comment]
Replaces #385: @adamobeng @matthewguitar89 @zachcp are also available.
