### ISSUE TITLE
Automatically build PDF and PNG versions of ODPs

### ISSUE THREAD

**Issue by wking** [swcarpentry/DEPRECATED-website#5]
The current Subversion repository tracks PDF and PNG versions of some ODP slides.  Rather than bloat the repository with a bunch of binary blobs, we should automatically generate them using LibreOffice and Imagemagick.

Potential issues with autogeneration:
1. The SWC server doesn't have the new build tools installed.  Fix: build a tarball locally, push the tarball to the server, and unpack there:
   
   $ make swc-website.tar.gz
   $ scp swc-website.tar.gz server:/downloads/dir/
   $ ssh server tar -xzf /downloads/dir/swc-website.tar.gz -C /target/dir
2. Contributing devs may not have the new build tools installed.  Fix: have them grab the tarball from the SWC server and use it to seed their local build.
   
   $ wget http://server/downloads/swc-website.tar.gz
   $ tar -xzf swc-website.tar.gz -C /tmp/swc/
   $ git clone git://github.com/swcarpentry/website.git
   $ cd website
   $ make PDF_DST= PNG_DST= site

**Comment by jiffyclub** [comment]
I'd be more interested in an actual plan for media. The 4.0 stuff is never going to change so I don't think it's too important that we go to a bunch of trouble to auto generate it. Right now the repo is at a fairly manageable ~300 MB, but what are we going to do as we continue to add media for blog posts, etc? Just assume it won't grow very fast?

**Comment by wking** [comment]
On Tue, Dec 11, 2012 at 07:37:12PM -0800, Matt wrote:

> I'd be more interested in an actual plan for media.

I agree with this, but it probably deserves its own issue.

> The 4.0 stuff is never going to change so I don't think it's too
> important that we go to a bunch of trouble to auto generate it.

It's not a lot of trouble, I've already written up the patch :p.  And
I think “never going to change” is an exaggeration, otherwise why
bother with version control at all?

**Comment by jiffyclub** [comment]
No, I'm serious. Never, ever change. And if we can come up with a good media plan I'd be happy to see it stay out of version control.

@gvwilson is the one who's is probably most often going to be compiling the site so I think it's up to him to decide what work flow he'll be happy with.

**Comment by wking** [comment]
On Wed, Dec 12, 2012 at 08:04:10AM -0800, Matt wrote:

> No, I'm serious. Never, ever change. And if we can come up with a
> good media plan I'd be happy to see it stay out of version control.

Really?  It's perfect now?  Noone will ever improve anything?  Or
migrate to a different file format when the current ODP eventually
dies?

> @gvwilson is the one who's is probably most often going to be
> compiling the site so I think it's up to him to decide what work
> flow he'll be happy with.

Works for me.

**Comment by jiffyclub** [comment]
@gvwilson can correct me, but I think we are completely done with ODP/PPT formats. New content will be in something else (e.g. IPython Notebooks for anything Python related).

**Comment by gvwilson** [comment]
On 2012-12-12 11:16 AM, Matt wrote:

> @gvwilson https://github.com/gvwilson can correct me, but I think we
> are completely done with ODP/PPT formats. New content will be in
> something else (e.g. IPython Notebooks for anything Python related).

That is my strong preference, though #include years of discussion about 
what's wrong with current-generation HTML as a slideshow format...
G

**Comment by embray** [comment]
Yeah I really like some of those slide decks and I think they're worth having around; I just don't want to be the one who converts them to HTML. (Or we could just put up a big &lt;canvas&gt; and write JS to draw directly to it; honestly that would be less hassle than positioning divs).

**Comment by wking** [comment]
On Wed, Dec 12, 2012 at 08:18:29AM -0800, Greg Wilson wrote:

> On 2012-12-12 11:16 AM, Matt wrote:
> 
> > @gvwilson https://github.com/gvwilson can correct me, but I think we
> > are completely done with ODP/PPT formats. New content will be in
> > something else (e.g. IPython Notebooks for anything Python related).
> 
> That is my strong preference, though #include years of discussion about 
> what's wrong with current-generation HTML as a slideshow format...

“Development in this direction is dead” definitely sounds like a good
reason to not transfer this content into the new Git repository.  If
the material doesn't come into the new repository, there's no need for
my patch.

I was under the impression that while further development of the ODP
source was not very palatable, it was still Greg's lesser of N evils.
Until there is a successor in place, it seems like we're stuck with
ODP.  In that case, I still think my build patch is useful.

**Comment by jiffyclub** [comment]
I think we've concluded that the lack of development on this section of Software Carpentry makes it unnecessary to worry about this. For the time being we're just going to add everything to the git repo. One size mitigation we might make in the future is to move the `3_0` and `4_0` directories to separate repos and add them as submodules in this repo.

**Comment by jiffyclub** [comment]
Actually, I went ahead and did the submodules thing to keep the size of the main repo down.
