### ISSUE TITLE
Boot camp at Simon Fraser University June 2013

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#502]
Please add a comment to this ticket if you're available to help teach at SFU in June.

**Comment by BernhardKonrad** [comment]
Hi, I could help if it's before June 15th.

**Comment by LJWilliams** [comment]
I'll be in Vancouver then.  So I would be glad to help.

Lynne

**Comment by jooolia** [comment]
I could potentially help. Depends on how some data come back. :)
