### ISSUE TITLE
Link to blog from index.html in compiled web site broken

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#51]
index.html has "./blog/" as a link, but that 404's on http://dev.software-carpentry.org --- rewrite issue?

**Comment by pipitone** [comment]
Fixed in svn rev 3409.

**Comment by gvwilson** [comment]
On 2012-12-12 10:45 AM, pipitone wrote:

> Fixed in svn rev 3409.

This fixes the .htaccess, but leaves the link in index.html as "./blog/" 
--- should it be "./blog/index.html"?
Thx,
G
