### ISSUE TITLE
Revise pre-assessment questionnaire

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#512]
# Pre-Boot Camp Skills Survey

Please answer the following questions to the best of your ability.  to
help your instructors learn more about who they will be teaching and
what pace and level would be most useful.

Your name: ________________________________________

Email address: ________________________________________

Do you plan to attend the workshop at [location]?
- Yes
- No
- Maybe: ________________________________________

Are you currently registered for this workshop?
- Yes: registration confirmed
- Yes: waitlist
- No
- Don't know

What is your career stage?
- Undergraduate
- Graduate
- Post-doc
- Faculty
- Industry
- Support staff
- Other: ________________________________________

What is your primary field of work?
- Mathematics
- Astronomy
- Physics
- Chemistry
- Medicine
- Economics
- Administration
- Earth sciences
- Ecology/zoology/botany
- Biology/genetics
- Engineering (civil, mechanical, chemical, etc.)
- Computer science/electrical engineering
- Humanities and social sciences
- Tech support, lab technician, support programmer
- Other: ____________________

Please describe your current field of work in a couple of sentences:
- ________________________________________
- ________________________________________

Please describe how you would like to use computers in your research:
- ________________________________________
- ________________________________________

What operating system do you use on the laptop you are bringing to the
boot camp?
- Linux
- Mac OS X
- Windows

What programming language(s) are you comfortable with (if any)?:
- ________________________________________

What best describes how you currently program?
- I never have.
- I have, but don't.
- I write a couple of dozen lines every once in a while to analyze data for my own use.
- I write a few hundred lines a month that other people occasionally use.
- I regularly work on large, complicated programs.

What three computing tools do you use most frequently in your
research?  (Please do not include tools that aren't specific to
research, such as word processors, browsers, or music players.)
1. ________________________________________
2. ________________________________________
3. ________________________________________

Please help us get a better sense of your current skills by telling us
how you'd do on the following tasks:
## Programming:

A tab-delimited file has two columns showing the date and the
highest temperature on that day.  Write a program to produce a graph
showing the average highest temperature for each month.
- I wouldn't know where to start
- I couldn't do it with a program, but I could do it with a spreadsheet
- I could probably struggle through writing a program
- I could do this task easily
## Shell:

A directory contains 1000 text files.  Create a list of all files
that contain the word "Drosophila" and save the result to a file
called results.txt.
- I would use "Find in Files" and "copy and paste"
- I could probably struggle through it using the shell
- I could easily do this task in the shell using a pipeline of several commands
## Version Control:

Given the URL for a project on GitHub, check out a working copy of
that project, add a file called notes.txt, and commit the change.
- What's GitHub?
- I wouldn't know where to start
- I could struggle through it
- I could do this task easily
## Testing:

Given a 200-line function to test, write half a dozen tests using a
unit testing framework and use code coverage to check that they
exercise every line of the function.
- What's a unit testing framework?  And what's code coverage?
- I wouldn't know where to start
- I could struggle through it
- I could do this task easily
## Databases:

A database has two tables Scientist and Lab.  Scientist's columns
are the scientist's user ID, name, and email address; Lab's columns
are lab IDs, lab names, and scientist IDs.  Write an SQL statement
that counts the number of scientists in each lab.
- I wouldn't know where to start
- I could struggle through it
- I could do this task easily

**Comment by HaveF** [comment]
Maybe leave a open question like this?

**(optional)Your daily work time may be wasted on some duplicate work. You're sure you will get free if you know some easy-to-use programming language. So, do you like to tell us about this duplicate work?**

**Comment by rmdickson** [comment]
I like the suggestion from @HaveF.  It provides the instructors with the possibility of customized examples targeted precisely at (at least one member of) their audience.  Let me propose another phrasing:

OPTIONAL:  Can you think of a computing task, relevant to your research, that is repetitive or error-prone?  It might involve manual operations, for example:  Click here, drag there, scan for this, type in that.  Have you ever said to yourself, "There must be a better way to do this"?  Describe the task:

**Comment by onnodb** [comment]
May I suggest putting in some text like "Filling in this survey should take about 10 minutes max" at the start? It may help increasing response rates.

**Comment by goxberry** [comment]
I would suggest adding something like "Have you used a text editor (not a word processor like Microsoft Word, etc.) before?"

At the UCB boot camp two weekends ago, I asked how many people hadn't used a text editor other than Word before, and over two-thirds of the room put their hands up. I think it's a skill that could be self-taught prior to boot camps, and makes some of the live coding demonstrations for the shell (and version control!) _so much_ easier.

Sublime Text 2 is a good editor to recommend to novices, since it's fully functional without ponying up $70 for a license, aside from annoying notifications to buy a license every so often -- every 50 saves, I think. For basic functionality (cut, copy, paste, save), keyboard shortcuts follow OS standards, plus there's a GUI. The only semi-awkward issue with Git is using it as an editor for commits, which can be solved with configuration (or just using `git commit -m`, I suppose).

**Comment by wking** [comment]
I like this trimmed down survey, and I agree with the other comments
(which I agree with except for the Sublime plug ;).  However, a
trimmed pre-assessment won't be as useful for pre/post comparisons
that gauge our effectiveness.  On the other hand, a short
pre-assessment that we actually collect data for is better than a long
one that we don't use ;).  For instructors who aren't going to do a
full blown survey of their users, I think this survey mostly hits the
right balance, except for:

```
Fri, Apr 26, 2013 at 05:07:53AM -0700, Greg Wilson:
> Do you plan to attend the workshop at [location]?
> * Yes
> * No
> * Maybe: ________________________________________
```

Do you expect anything other than “Yes” or “Maybe: waitlisted”?  I
don't really see the point here.

```
> What three computing tools do you use most frequently in your
> research?  (Please do not include tools that aren't specific to
> research, such as word processors, browsers, or music players.)
```

I'd like a few examples to help students strike the right balance.  I
imagine you're looking looking for language-level stuff (Excel,
LabVIEW, Python, R, …) and not for underlying libraries (GTK, MPI,
OpenCL, Comedilib, …), but clarification would be nice.  On the other
hand, our students are probably not using all that many libraries
directly.  Three is also a small list ;).  Why not have it be “as many
as you can fit” (on paper) or “up to ten” online.

```
>   A directory contains 1000 text files.  Create a list of all files
>   that contain the word "Drosophila" and save the result to a file
>   called results.txt.
>   * I would use "Find in Files" and "copy and paste"
>   * I could probably struggle through it using the shell
>   * I could easily do this task in the shell using a pipeline of several commands
```

No pipeline required for GNU grep:

```
grep -rl Drosophila . > results.txt
```

The `-r` option for grep is not in POSIX 2013, but `-l` is.  I'd just
say “I could easily do this task in the shell”, and not talk about
pipelines.

```
>   Given a 200-line function to test, write half a dozen tests using a
>   unit testing framework and use code coverage to check that they
>   exercise every line of the function.
```

I've never seen a 200 line function that I could fully exercise in 6
tests ;).

**Comment by gvwilson** [comment]
Further information (via @picken19)
1. This is a "skills survey" to be done ~2 weeks before the workshop.
2. Instructors can analyze the data quickly and easily (once we post a script to do so).
3. It is designed to get information about the audience so that instructors can target their lectures at the appropriate level.

**Comment by gonuke** [comment]
"3. It is designed to get information about the audience so that instructors can target their lectures at the appropriate level."

I think this should be in the survey text to reassure students.  That is, I worry that some students will interpret these questions as a pre-"test" rather than a pre-"survey"
