### ISSUE TITLE
Bootcamp for RAL between 17/06 and 05/07

### ISSUE THREAD

**Issue by mikej888** [swcarpentry/DEPRECATED-website#515]
Tom Griffin (STFC, RAL, ISIS) is interested in a boot camp STFC [ISIS Facility](http://www.isis.stfc.ac.uk/) is the UK's pulsed neutron and muon source) at the Rutherford Appleton Laboratory in Oxfordshire.

Good dates are constrained by the operation periods of the facility ('cycles'). We have a period of downtime from 17th June - 5th July which would be ideal.

Paying expenses will not be a problem (we can provide on-site accommodation (convenient but remote) or in a nearby town, whichever they prefer).

Attendees would be instrument scientists, PhDs and post-docs: typically physicists, chemists and biologists who use and write software to analyse data. Will open out to other local scientists if space.

Most analysis at ISIS is done using a tool called [Mantid])http://www.mantidproject.org/). Mantid is a data analysis framework which allows custom algorithms to be imported (Python or C++), and has a large number of built in algorithms, which are accessible via a GUI, or can be scripted together using Python. Inevitably, scientists still develop mini tools, which can grow and grow.

Cover an agenda very similar to the example on http://software-carpentry.org/bootcamps/how-to.html Perhaps without the shell component (like it or not, Windows in the default desktop at RAL) and concentrating on Git in the version control
section.

**Comment by karthik** [comment]
I'm interested. I can do after June 23rd but before is harder. Also, I'm based out of San Francisco.

**Comment by mikej888** [comment]
Given it's now very short-notice and Tom's absence till the 10th I've suggested this not go ahead at this time. We can discuss other possible dates.
