### ISSUE TITLE
Kansas boot camp in August

### ISSUE THREAD

**Issue by amyrhoda** [swcarpentry/DEPRECATED-website#518]
Is it going to be hot? You bet it is. But it's a dry heat. Who's in?

**Comment by amyrhoda** [comment]
Damn, Wikipedia says it's not dry in Kansas at all. Sorry folks! Maybe we can do a camp in Saskatchewan sometime.

**Comment by snacktavish** [comment]
I'm moving to KU this month! I'm IN.
