### ISSUE TITLE
Default new-look web site font size too small

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#53]
General-purpose text needs to be a point size or two larger for older eyes :-)

**Comment by pipitone** [comment]
Fixed in svn rev 3410.

**Comment by jiffyclub** [comment]
What did you change it to? I'm okay with 15px but 16px is too big.

**Comment by pipitone** [comment]
Oh dear.  Yes, I changed it to 16pt.  It looks reasonable on my machine under chrome/firefox.

**Comment by jiffyclub** [comment]
At 16px I think the font is weighty enough that it starts to look bold and conflict with `<strong>` text.
