### ISSUE TITLE
Boot camp at Woods Hole Oceanographic Institution (MA) in October

### ISSUE THREAD

**Issue by amyrhoda** [swcarpentry/DEPRECATED-website#533]

**Comment by selik** [comment]
Tentative Yes.

**Comment by emhart** [comment]
I'm not local but I know woodhole and the cape so I'd also like to be a tentative yes if there's travel funds

**Comment by amyrhoda** [comment]
Cool, thanks -- I've added @selik and @emhart as tentative instructors. Dates will be Nov 14-15 -- let me know if that changes your answer.

**Comment by emhart** [comment]
Unfortunately I have a meeting on Nov 14-15 in San Francisco, so I can't teach this :(
