### ISSUE TITLE
Add location highlighting to new-look web site

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#55]
Everybody except @gvwilson seems to want some sort of nav-bar highlighting to show current location.

**Comment by jiffyclub** [comment]
The highlighting can be achieved by setting the current navbar `<li>` item's class to `active`. The tricky part is making it so that every page knows which navbar item to fiddle with, though we might be able to set this at compile time using information available to Jinja.

**Comment by jiffyclub** [comment]
I added location highlighting in r3421 to the the SVN repo. Which, incidentally, should be the last update to the website via SVN!
