### ISSUE TITLE
Remove 'Home' link from main menu?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#56]
If clicking on the logo at the top of the page takes people home, do we also need a 'Home' link?

**Comment by gdevenyi** [comment]
Yes, because it is not immediately obvious to all users that
1) The logo is clickable
2) The logo will send you home

**Comment by jiffyclub** [comment]
It's become pretty standard practice to make logos send you back to the home page so I think users expect that, but I don't think the "Home" link is hurting anything by taking up space in the navbar.

**Comment by gvwilson** [comment]
Leaving site design as is.
