### ISSUE TITLE
Use human-friendly date format on blog entries instead of YYYY-MM-DD

### ISSUE THREAD

**Issue by karthik** [swcarpentry/DEPRECATED-website#58]
This is more of a UI suggestion but it would nice to make the dates on [the blog index page](http://dev.software-carpentry.org/blog/index.html) more human friendly.

![image](https://f.cloud.github.com/assets/138494/8588/afa2b172-447a-11e2-8c49-1a91d6d811c3.png)

**Comment by wking** [comment]
On Wed, Dec 12, 2012 at 08:41:00AM -0800, Karthik Ram wrote:

> This is more of a UI suggestion but it would nice to make the dates
> on [this page](http://dev.software-carpentry.org/blog/index.html)
> more human friendly.

Hey, I like YYYY-MM-DD ;).  It has sane significant digit ordering,
and it avoids MM/DD/YYYY|DD/MM/YYYY cultural issues (e.g. "December
12, 2012" vs. "12 December 2012").

**Comment by karthik** [comment]
The sanity is great for research and programmatic needs and the date can still be stored in the database as `YYYY-MM-DD`. But this is a website with some aesthetic needs and dates could be formatted in a better way. There would be less cultural confusion with a version below than the one currently in place. How would there be any confusion with this format ("December 12, 2012" vs. "12 December 2012")?

![image](https://f.cloud.github.com/assets/138494/8634/c3464124-447c-11e2-94a6-5939e507380c.png)

**Comment by jiffyclub** [comment]
A large badge like that is totally out of the question, though. These "long past" blog entries should only take up one line.

**Comment by karthik** [comment]
I should have been more clear. It doesn't have to be a large badge. I was merely pointing out an example of dates that are easier to read. It could easily just be plain text. `9th June, 2010` is so much friendlier than `2010-06-09`. But I'll stop here and not belabor the point.
