### ISSUE TITLE
Add drop-down menus to web site

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#59]
(split from #55)

Everyone but @gvwilson wants drop-down menus on the web site.

**Comment by jiffyclub** [comment]
I'm not so sure about that "everyone". And for several of the menu items I'm not actually sure what would go in the drop down. You've done a good job putting links to the most useful information at the top of each sub-page so I'm not sure drop-downs would add much navigational help.

**Comment by karthik** [comment]
Since the framework is Bootstrap, this is easy and [readily available](http://twitter.github.com/bootstrap/components.html#dropdowns). I'm indifferent on this matter but it would make site navigation easier. `About`, for example, could have a dropdown with 
- Credits
- Our Team
- Our Audience
- Testimonials
- How to Contribute
- Reading 

With bootcamps it could be **upcoming** and **past**. I'd say this isn't a priority but might be useful to implement down the line.

**Comment by gvwilson** [comment]
On 2012-12-12 1:31 PM, Karthik Ram wrote:

> |About|, for example, could have a dropdown with
> - Credits
> - Our Team
> - Our Audience
> - Testimonials
> - How to Contribute
> - Reading

In that particular case, I'd actually get rid of the 'About' page 
entirely (since the key information is on the home page).

**Comment by karthik** [comment]
Definitely, that makes sense.

**Comment by caitsydney** [comment]
Agreed about the ease of site navigation. 

For example, getting to Boot Camp > FAQ and Bootcamp > How to Run a Boot Camp can only be accomplished by first going to the Boot Camp page and then looking through the text for the appropriate links. Might increase site traffic to these sub-pages if drop-down menus are implemented? Not sure if there's a reason that the menus haven't been implemented this way already.

**Comment by jiffyclub** [comment]
I think @gvwilson had some technical aversion to them based on his experience on the existing site. But with Bootstrap I don't worry too much about that, I think their code is high quality.

We just need a good map of what goes in the drop downs. The existing menus on http://software-carpentry.org are rather overloaded and I don't want to just duplicate those.

**Comment by karthik** [comment]
Agreed. The current version is daunting. All the lectures don't need to be on there. And License could be moved to the footer (a location where people typically look for it) to save space up top.

**Comment by LJWilliams** [comment]
Maybe not dropdown boxes, but a navigation bar underneath the main header and links to the relevant subpages?
