### ISSUE TITLE
Add key to Google Map explaining pin color

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#61]
We're using blue and purple to show future and past workshops; the map should have a key.

**Comment by wking** [comment]
On Wed, Dec 12, 2012 at 08:45:22AM -0800, Greg Wilson wrote:

> We're using blue and purple to show future and past workshops; the
> map should have a key.

Is this independent of #21 [1](https://github.com/swcarpentry/website/issues/21)?

I think the map should be auto-generated using the GitHub API and the
`latlng` metadata from the boot camp page.  Along the lines of the
proposed Jekyll-generated map [2](https://github.com/jiffyclub/boot-camps/tree/map-calendar), but addapted to compile.py and
Jinja.  I'm not sure if a translation of that work to Jinja should be
attached to #21 or to this issue.

```
 https://github.com/jiffyclub/boot-camps/blob/map-calendar/_includes/map-header.html
 https://github.com/jiffyclub/boot-camps/blob/map-calendar/_includes/map-body.html
```

**Comment by gvwilson** [comment]
The key (pin color <=> meaning) is a static thing, while the map itself 
is dynamic, so I thought these would be two separate fixes.
