### ISSUE TITLE
fix creative commons cc by badge to show content owners

### ISSUE THREAD

**Issue by ahmadia** [swcarpentry/DEPRECATED-website#63]
The Creative Commons badge should probably look something more like:

<a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a> This site, by the <a xmlns:cc="http://creativecommons.org/ns#" href="http://software-carpentry.org" property="cc:attributionName" rel="cc:attributionURL">Software Carpentry Team</a>, is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a>.

**Comment by wking** [comment]
On Wed, Dec 12, 2012 at 08:59:36AM -0800, ahmadia wrote:

> …the Software Carpentry Team…

This should probably link to a list of contributors, instead of
linking to the SWC homepage.

**Comment by ahmadia** [comment]
Agreed, I was just mocking something up quickly.

**Comment by wking** [comment]
On Wed, Dec 19, 2012 at 01:56:22PM -0500, W. Trevor King wrote:

> This should probably link to a list of contributors, instead of
> linking to the SWC homepage.

After #177 gets in (assuming it does), generating a list of
contributors is easy:

   $ git log --pretty='format:%aN <%aE>' | sort | uniq

Of course, without history from the Subversion years, we'll probably
have to add some additional tweaks.  For most of my projects, I use my
update-copyright helper script [1](http://pypi.python.org/pypi/update-copyright/) to maintain this sort of thing.

```
 http://blog.tremily.us/posts/update-copyright/
```
