### ISSUE TITLE
Update Twitter followers

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#634]
The swcarpentry account on Twitter follows many people who are not instructors, helpers, etc. We should cut this back to make the retweet stream easier to manage.

**Comment by npch** [comment]
You could use the new and improved Twitter lists functionality to make this
easier:
http://mashable.com/2013/05/30/twitter-lists-2/

On 5 July 2013 04:16, Greg Wilson notifications@github.com wrote:

> The swcarpentry account on Twitter follows many people who are not
> instructors, helpers, etc. We should cut this back to make the retweet
> stream easier to manage.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/swcarpentry/website/issues/634
> .

## 

Neil Chue Hong
Director, Software Sustainability Institute
EPCC, University of Edinburgh, JCMB, Edinburgh, EH9 3JZ, UK
Tel: +44 (0)131 650 5957
http://www.software.ac.uk/

LinkedIn: http://uk.linkedin.com/in/neilchuehong
Twitter: http://twitter.com/npch
ORCID: http://orcid.org/0000-0002-8876-7606
