### ISSUE TITLE
Boot camp in LA, October 29, Paleontologists

### ISSUE THREAD

**Issue by amyrhoda** [swcarpentry/DEPRECATED-website#639]
Please comment if you're interested in helping or instructing at a boot camp associated with the annual meeting of the Society of Verterbrate Paleontology. http://vertpaleo.org/PDFS/38/384896a1-56c6-4cf5-b936-fbde86e5a2b7.pdf, page 28.

**Comment by karthik** [comment]
I'm down to co-instruct.

**Comment by ptone** [comment]
Is it know whether this will span Halloween?

If this is just before or just after the meeting itself, I'd be interested in helping out with this one. I'm somewhat local, and my PhD was in the area of vertebrate evolution.

**Comment by amyrhoda** [comment]
@ptone, it's on Oct 29 -- just a one-day camp.

@karthikram, you're in as an instructor, and it turns out April Wright is also instructing, but I think we can use more helpers - -sounds like it's going to be a big group.

**Comment by karthik** [comment]
@amybrown Given the lack of funding for travel I unfortunately must bow out. I hope you are able to find other local instructors/helpers.
