### ISSUE TITLE
Add upcoming workshops to the homepage

### ISSUE THREAD

**Issue by karthik** [swcarpentry/DEPRECATED-website#64]
The home page looks sparse. It would be great to have a sidebar with a list of upcoming workshops and links to them.

**Comment by gvwilson** [comment]
Agree that existing home page is sparse; if enough other people like a list of upcoming boot camps, that's doable (though a bit painful given our existing web site compiler).

**Comment by jiffyclub** [comment]
Actually, if we migrate the boot camps section to the boot-camps repo as I plan to this will become really difficult.

**Comment by wking** [comment]
On Wed, Dec 12, 2012 at 09:11:25AM -0800, Matt wrote:

> Actually, if we migrate the boot camps section to the boot-camps
> repo as I plan to this will become really difficult.

What would the options be?  The boot-camps site could expose something
that the main website would include in an iframe.  The boot-camps site
could also export some JSON which some JS on the main website to
unpack it into a list.  Neither one of those sounds like lots of fun,
but maybe they wouldn't be as bad as I think.  There may also be
another way to do this that I'm not aware of ;).

**Comment by gvwilson** [comment]
Should be part of the Pelican rewrite.

**Comment by gvwilson** [comment]
Added to new-look web site.
