### ISSUE TITLE
Boot camp at Harvard, August-September

### ISSUE THREAD

**Issue by amyrhoda** [swcarpentry/DEPRECATED-website#640]
Please comment if you're available to instruct or help at a weekend boot camp at Harvard in late August or early September. Let me know your preferred dates in that range.

**Comment by selik** [comment]
Willing and able. Local, so whenever is OK.

**Comment by amyrhoda** [comment]
Cool, thanks Michael.

**Comment by bitdancer** [comment]
I could help out with this.  I'm not available the first weekend in September (31st/1st), but other weekends are clear at the moment.
