### ISSUE TITLE
Disqus comments should not be enabled on all pages

### ISSUE THREAD

**Issue by karthik** [swcarpentry/DEPRECATED-website#66]
Disqus comments should not be default on all pages. For example, there is no need for anyone to comment on the credits or [team](http://dev.software-carpentry.org/about/team.html) pages.

**Comment by gvwilson** [comment]
It's an easy way for people to report typos --- should we provide a 
mailto: link instead?
Cheers,
Greg

**Comment by karthik** [comment]
Typos and errors are better suited for email (IMO) because once a typo or error is fixed, the comments are no longer relevant and the context would be lost. You can't _close_ a comment like a GitHub issue. So yes, I'd vote for a mailto link over comments for such issues.

**Comment by gvwilson** [comment]
We can delete comments, but you're right, that's not the same as closing 
them.  #68 will take care of this...

**Comment by gvwilson** [comment]
Can @karthikram please provide a list of pages that _shouldn't_ have Disqus comments?

**Comment by karthik** [comment]
http://software-carpentry.org/about/index.html
http://software-carpentry.org/license.html (although weird that there is already a comment there from a month ago. questions about licenses might still be better suited to email though).
http://software-carpentry.org/about/credits.html
http://software-carpentry.org/about/team.html
http://software-carpentry.org/about/audience.html
http://software-carpentry.org/about/testimonials.html (it would be good to have a link at the bottom here saying "submit one!" in case any past participants are compelled to do so).
http://software-carpentry.org/blog/index.html (only the main blog page. We do need it on individual posts though).

Not entirely sure about these pages (I'll leave the decision up to you)
http://software-carpentry.org/about/biblio.html
http://software-carpentry.org/bootcamps/index.html
