### ISSUE TITLE
Change default font on the css

### ISSUE THREAD

**Issue by karthik** [swcarpentry/DEPRECATED-website#67]
More readable web fonts (and consistent user experience) can be achieved using web fonts. I'd strongly recommend [Adobe Edge Fonts](http://html.adobe.com/edge/webfonts/) which are free and I frequently use them in my [web deck presentations](http://inundata.org/ecolunch). 

For source code (`pre` and `code`), I'd recommend [source code pro](http://blogs.adobe.com/typblography/2012/09/source-code-pro.html).
For other text, [Quattrocento Sans](http://www.impallari.com/projects/overview/quattrocento-sans-family) or [Gentium book basic](http://www.google.com/webfonts/specimen/Gentium+Book+Basic).

**Comment by jiffyclub** [comment]
I'll just paste in an email we got from Jeffrey Shelton:

> A combination of serif and sans-serif fonts would improve the site's readability, I believe. This can be fairly easily accomplished using Google's Web Fonts (http://www.google.com/webfonts). In particular, I might try a serif font for headlines (say Bree Serif or Cantata One), and a sans-serif font (Gudea or Imprima) for body text. Or to keep it simple, try Droid Serif for headlines and Droid Sans for text.

**Comment by gvwilson** [comment]
Leaving fonts as they are for now.
