### ISSUE TITLE
Move contact information to the footer

### ISSUE THREAD

**Issue by karthik** [swcarpentry/DEPRECATED-website#68]
In general people may find the need to contact SWC from any page on the site. It makes good (web design) sense to have this information readily accessible from everywhere. I'd suggest making it available in the footer alongside the CC license.

**Comment by pipitone** [comment]
Greg suggests "Report a bug" rather than a contact link.   I've  committed this as 59ba4ef in my repo.

**Comment by pipitone** [comment]
Fixed in 246b38

**Comment by jiffyclub** [comment]
As @pipitone said, added in 246b38f.
