### ISSUE TITLE
Add contributor guidelines

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/DEPRECATED-website#69]
Each of our repos should have a [contributing guidelines](https://github.com/blog/1184-contributing-guidelines) file spelling out the expected format and content of material for that repo.

**Comment by wking** [comment]
This is related to the DCO comment I made for the boot-camps repository: https://github.com/swcarpentry/boot-camps/pull/1#issuecomment-11295191

I can write up a similar PR for this repository once someone tells me we're ready to move forward.

**Comment by jiffyclub** [comment]
I've started working on some guidelines for the boot-camps and notebooks repos.

**Comment by wking** [comment]
Was this fixed with #203, or do we still need more format/content guidance?

**Comment by jiffyclub** [comment]
Still waiting on swcarpentry/notebooks#5.

**Comment by wking** [comment]
Looks like swcarpentry/notebooks#5 was just merged.  Anything else before we close this issue?

**Comment by jiffyclub** [comment]
Fine with me.
