### ISSUE TITLE
Implement code of conduct for workshops

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#7]
Borrow from the [PyCon Code of Conduct](https://us.pycon.org/2012/codeofconduct/) to create one for Software Carpentry workshops.
- Is this opt-in or mandatory?

**Comment by codersquid** [comment]
The Chicago Python Workshop created a [code of conduct](https://openhatch.org/wiki/Chicago_Python_Workshop/Code_of_Conduct) tailored for a beginning workshop in one room with a duration of a day and a half.

**Comment by ethanwhite** [comment]
Since we're not charging folks to attend we could remove references to a lack of refunds in statements about participants being asked to leave.

**Comment by gvwilson** [comment]
On 2012-12-17 10:42 AM, Ethan White wrote:

> Since we're not charging folks to attend we could remove references to a
> lack of refunds in statements about participants being asked to leave.

Some boot camps are going to try out a nominal fee (e.g., $20) to cut 
down on no-shows.  We should probably modify the wording to say "refund 
fee if one was charged" or "refund any fee that may have been charged" 
or the like?

**Comment by ethanwhite** [comment]
Sounds good. I like the second option.

**Comment by katyhuff** [comment]
Instead of "fee," you could call it a "deposit" or an "attendance deposit."

**Comment by gvwilson** [comment]
Completed.
