### ISSUE TITLE
Create cheat sheets for boot camp participants

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#70]
Every topic should have a cheat sheet for participants to refer to (and to keep instructors on topic).

**Comment by karthik** [comment]
I can help with the ones for R and Git. This would be great to develop on the wiki for this repo. If written in markdown, it could easily be converted to pdf for handouts, posting elsewhere etc.

**Comment by jiffyclub** [comment]
I'd say this should go into the [boot-camps repo](https://github.com/swcarpentry/boot-camps). And not in the wiki, but as actual content.

**Comment by gvwilson** [comment]
Superceded by #149, #150, #151, #152, #153, and #154.
