### ISSUE TITLE
Convert software-carpentry.org email forwarding addresses into real acounts.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#71]
admin@software-carpentry.org, info@software-carpentry.org, etc., all forward to @gvwilson right now --- they should instead be real accounts (or all forward to one real account) so that:
1. Project email isn't archived in @gvwilson's private mail folder, and
2. Other people (plural) can deal with things.

**Comment by pipitone** [comment]
I made sure that all of the forwarding addresses now all forward to admin@.  I figure we can fork off full fledge email addresses (rather than forwarding ones) if/when we have someone to manage them.
