### ISSUE TITLE
Add matplotlib to NumPy chapter in instructor's guide

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#72]
The NumPy discussion in book/numpy.html should include a brief introduction to plotting.

**Comment by ethanwhite** [comment]
I'm happy to help with this.

**Comment by ahmadia** [comment]
We have some material that could be reused from
https://github.com/pyhpc/pyhpc-tutorial

If you want to add plotting, @gvwilson, then I suggest you consider
renaming the section to something like "scientific computing with Python",
as the actual numpy stack is sort of 1/3 of the matplotlib/scipy/numpy
trifecta that make up the basics.

A

**Comment by joonro** [comment]
I'm happy to contribute as well!
