### ISSUE TITLE
Move 3_0 and 4_0 templates into website repo

### ISSUE THREAD

**Issue by jiffyclub** [swcarpentry/DEPRECATED-website#73]
The [3.0](https://github.com/swcarpentry/lessons_3_0) and [4.0](https://github.com/swcarpentry/lessons_4_0) lesson material is in separate repos to keep the size of the main one down. This is great for the lesson data but inconvenient for the lesson page templates, which may need to be updated frequently as the design of the site evolves.

We should move the templates into the main repo and have the build script put the compiled HTML together with the lesson images.

**Comment by gvwilson** [comment]
I think 4_0/_lesson.html, 4_0/_topic.html, and 3_0/_slideshow.html should stay where they are --- it seems more natural to keep the templates with the things that use them.

**Comment by gvwilson** [comment]
Leaving as is.
