### ISSUE TITLE
Make bin/*.py work with Python 2.6.6

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#75]
The host for software-carpentry.org has Python 2.6.6 installed, which:
- doesn't have set comprehensions, and
- has an older version of the ElementTree library for XML

This means we can't run bin/links.py (which uses bin/util.py) to check things after building the web site.  Obviously bad, needs fixed.

**Comment by wking** [comment]
On Fri, Dec 14, 2012 at 10:36:27AM -0800, Greg Wilson wrote:

> The host for software-carpentry.org has Python 2.6.6 installed, which:
> - doesn't have set comprehensions, and
> - has an older version of the ElementTree library for XML

These should have been fixed by #118.

**Comment by gvwilson** [comment]
Fixed.
