### ISSUE TITLE
Some boot camps do not show up in calendar

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#86]
Looking at http://software-carpentry.org/bootcamps/index.html, some boot camps do not show up in the calendar. For example, the one-day boot camp on Jan 11 at UBC is not in the calendar, and neither is the two-day boot camp on Jan 21-22.

**Comment by jiffyclub** [comment]
This is still just an embed of @gvwilson's calendar, but I'm planning to redo the work @wking I did on #21 to bring it into the Jinja2 build system so that we generate our own calendar feed based on the presence of boot camp advertisement pages.

**Comment by gvwilson** [comment]
@gvwilson will update the Google Calendar.
