### ISSUE TITLE
Boot camp calendar should be as wide as the canvas

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#87]
The Google Calendar on the boot camp index page should be wider (preferably almost as wide as the rendering area). This might also fix the problem that the names of weekend bootcamps (e.g., the three on Jan 12-13) are cut in half and hence unreadable.

**Comment by jiffyclub** [comment]
You can do this currently just by setting `width="100%"` on the `<iframe>` element. Same with the map.
