### ISSUE TITLE
Where should the up-to-date teaching roster go?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#89]
Where should the list of who's teaching where, currently at http://teaching.software-carpentry.org/staffing/, be put long-term?  It's currently generated automatically from an SQLite database kept offline by @gvwilson (offline because it contains personal information about boot camp attendees and instructors).

**Comment by wking** [comment]
This looks like per-boot-camp metadata that should be stored with the
other metadata.  See, for example, [1](https://github.com/swcarpentry/website/issues/21#issuecomment-11451150).

**Comment by gvwilson** [comment]
Information on past boot camps can go in boot camp page metadata, but 
where do we store info on yet-to-be-scheduled not-yet-public 
still-in-discussion boot camps?

**Comment by wking** [comment]
On Wed, Dec 19, 2012 at 11:37:32AM -0800, Greg Wilson wrote:

> Information on past boot camps can go in boot camp page metadata, but 
> where do we store info on yet-to-be-scheduled not-yet-public 
> still-in-discussion boot camps?

If things are public/scheduled enough to go in
http://teaching.software-carpentry.org/staffing/, they should be ready
for an entry in bootcamps/.  Information that's more tentative will
probably go in the bootcamp issue (e.g. #26, [1](https://github.com/swcarpentry/website/issues/26)).

It's hard for me to imagine date/instructor information that is too
private to go in a bootcamp issue.  Perhaps a fictitious example would
help clarify the issue?

**Comment by wking** [comment]
See also, PR #334.

**Comment by gvwilson** [comment]
Existing storage mechanism is working well enough.
