### ISSUE TITLE
Use logo blue (#20267D) in web pages

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/DEPRECATED-website#99]
The dark blue in our logo is #20267D; we should use this in the web pages as well, but:
- Making h1-4 titles dark blue is ugly.
- Changing the color of the top menu items is hard (they're in bootstrap.css).

Maybe use dark blue buttons in the footer instead of gray?

**Comment by jiffyclub** [comment]
It's not that hard to change the navbar colors, I could do that.

We could change the link text color to that blue.

And I'll experiment with the footer elements.

**Comment by gvwilson** [comment]
On 2012-12-15 3:48 PM, Matt wrote:

> It's not that hard to change the navbar colors, I could do that.
> We could change the link text color to that blue.
> And I'll experiment with the footer elements.

Please go ahead and experiment with the navbar text colors and let me 
know what you think.  Ditto the footer elements.  Dunno about the links: 
the dark blue is hard to distinguish from black, esp. for old eyes or on 
small devices, so that probably won't work for usability.

**Comment by jiffyclub** [comment]
Here's a sample of what the navbar could look like turned `#20267D`:
![Screen Shot 2012-12-15 at 11 18 13 PM](https://f.cloud.github.com/assets/920492/15320/d66ddbe6-4737-11e2-8465-efc89acb956e.png)

**Comment by gvwilson** [comment]
Oh, I think I like that --- yes please.

**Comment by jiffyclub** [comment]
navbar pull request is #110. Anywhere else seem like a good candidate for blue-ification?

**Comment by pipitone** [comment]
Oh, I miss that purely text hero unit.  :-)  

I'm closing this since it's been a while and my impression is that the blue-ification is complete.
